### ISSUE TITLE
Converting Table from MyISAM to InnoDB

### ISSUE THREAD

**Issue by jandayanan** [robmorgan/phinx#1008]
Hi everyone.

Nice project and very useful. I ran into a question though, is it possible to change the Table engine from MyISAM to InnoDB AFTER being defined? The table I already have contains a MyISAM engine and we are looking to switching it to InnoDB. Is it possible? If so, how can I do so? (Note: I know it's possible to do it via raw query, but I am curious if this function exists natively, as changing engines may not be cross-platform)

**Comment by arnisjuraga** [comment]
We also are interested . Is it possible?

**Comment by semoriil** [comment]
This cannot be cross-platform, so writing migration with raw query should be OK. For compatibility just check that right DB adapter is used otherwise skip query.

**Comment by robmorgan** [comment]
As its MySQL specific you'll need to do this with raw queries e.g: `execute()` and `query()`. Phinx will never support this natively. Keep in mind this will stall writes until the engine has changed. More info: http://dev.mysql.com/doc/refman/5.0/en/alter-table.html.
