### ISSUE TITLE
Postgres - Support for Large Objects

### ISSUE THREAD

**Issue by costamauricio** [robmorgan/phinx#1021]
How can i create migrations with Large Object on Phinx? (eg.: lo_import)
There are any plans to implement this on Phinx core?
Or i should not use this kind of feature on db?

Tks.

**Comment by robmorgan** [comment]
Hi @costamauricio nothing is stopping you from using these functions in your migrations or seed classes, however Phinx will most likely never support them directly. Please use the `execute()` method to call these functions.
