### ISSUE TITLE
Add docs about MySQL table comment

### ISSUE THREAD

**Issue by piotr-cz** [robmorgan/phinx#1027]
In this PR #334 there was added new option to specify MySQL table comment, however it's missing in docs.
I'm not really sure in which place I should add it (probably new hading for MySQL specific options under [Creating a table](https://github.com/robmorgan/phinx/blob/v0.6.6/docs/migrations.rst#creating-a-table)), moreover I"m not really sure my english would be sufficient.

When looking at the [MySQL Adapter](https://github.com/robmorgan/phinx/blob/v0.6.6/src/Phinx/Db/Adapter/MysqlAdapter.php) specific options, there are two undocumented ones that probably should go to docs as well:

- **engine** default _InnoDB_
- **collation** default _utf8_general_ci_

**Comment by robmorgan** [comment]
hi @piotr-cz, no your English is good enough. Why don't you give it a shot and maybe I can edit it afterwards?

**Comment by piotr-cz** [comment]
Here it is

**Comment by robmorgan** [comment]
thanks
