### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by yashtodi94** [robmorgan/phinx#1032]
This is the error i get while trying to install phinx 0.6.6. Any ideas to solve it?

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for robmorgan/phinx dev-master -> satisfiable by robmorgan/phinx[dev-master].
    - Can only install one of: robmorgan/phinx[v0.6.6, dev-master].
    - Installation request for robmorgan/phinx ^0.6.6 -> satisfiable by robmorgan/phinx[v0.6.6].
Installation failed, reverting ./composer.json to its original content.

![image](https://cloud.githubusercontent.com/assets/18695133/22629144/a66efe98-ec06-11e6-8035-c1152b57b18f.png)

**Comment by robmorgan** [comment]
@yashtodi94 can I see your `composer.json` file?
