### ISSUE TITLE
How can I write tinyint(2) with phinx?

### ISSUE THREAD

**Issue by BassemN** [robmorgan/phinx#1037]
Hello,
How can I write `tinyint(2)` with phinx?
Thanks

**Comment by Munto** [comment]
Hello BassemN.

You can join the gitter channel to ask for help.
https://gitter.im/phinx-php/Lobby

I'm not sure that Github's issues are the right place to do it.

**Comment by BassemN** [comment]
@Munto Thank you very much :)
