### ISSUE TITLE
Chinese Doc

### ISSUE THREAD

**Issue by tsy12321** [robmorgan/phinx#1052]
hi
I translate your phinx doc into Chinese and look forwark you to link it in your 'Phinx Doc'.
(https://tsy12321.gitbooks.io/phinx-doc/content/introduction.html)

Look forward to your reply.

**Comment by robmorgan** [comment]
Hi @tsy12321, thank you so much for your contribution! Whilst I can't really read it, I trust you did a good job. I will make a link from the README. Rob

**Comment by tsy12321** [comment]
Thank you for accepting my doc and I will continue to maintain it.

**Comment by robmorgan** [comment]
added: https://github.com/robmorgan/phinx#documentation

**Comment by rquadling** [comment]
@tsy12321 Thank you for this. Do you have adequate tools in place to know what to update when we update the documentation?

**Comment by tsy12321** [comment]
@rquadling I watching this project now,do you have some good suggestion?
