### ISSUE TITLE
Add migration file name in phinxlog table for providing additional information

### ISSUE THREAD

**Issue by amyluo** [robmorgan/phinx#1057]
Our current work team is using phinx to maintain our MySQL DB schema and business logic related data updates. Due to the multiple devs work on same DB and many of us will change the DB by using migration file. So it happens when we switch from one branch to another branch, it is hard to track/remember which version(s) should rollback or migrate.

And sometimes I found I only saw version(s) up but the migration file was not on server's migrations folder and I didn't remember which branch brought in this migration version. 

So it will be nice to add additional column in phinxlog table to keep the migration file name in it. So even the migration file was been removed due to branch switch, dev can using phinxlog table as a trail to track down the migration file information.

**Comment by amyluo** [comment]
Sorry. This is a duplicated to issue #543

**Comment by rquadling** [comment]
This was added to Phinx in version 0.5.2
