### ISSUE TITLE
Minimum PHP version no longer compatible?

### ISSUE THREAD

**Issue by Beittil** [robmorgan/phinx#1058]
I have a web server with an PHP version 5.4.32 install, the installation guide says 5.4 and above should be sufficient to install Phinx, however I get the following errors when trying to run a 'composer install' command.

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for symfony/config v3.2.6 -> satisfiable by symfony/config[v3.2.6].
    - symfony/config v3.2.6 requires php >=5.5.9 -> your PHP version (5.4.32) does not satisfy that requirement.
  Problem 2
    - Installation request for symfony/console v3.2.6 -> satisfiable by symfony/console[v3.2.6].
    - symfony/console v3.2.6 requires php >=5.5.9 -> your PHP version (5.4.32) does not satisfy that requirement.
  Problem 3
    - Installation request for symfony/debug v3.2.6 -> satisfiable by symfony/debug[v3.2.6].
    - symfony/debug v3.2.6 requires php >=5.5.9 -> your PHP version (5.4.32) does not satisfy that requirement.
  Problem 4
    - Installation request for symfony/filesystem v3.2.6 -> satisfiable by symfony/filesystem[v3.2.6].
    - symfony/filesystem v3.2.6 requires php >=5.5.9 -> your PHP version (5.4.32) does not satisfy that requirement.
  Problem 5
    - Installation request for symfony/yaml v3.2.6 -> satisfiable by symfony/yaml[v3.2.6].
    - symfony/yaml v3.2.6 requires php >=5.5.9 -> your PHP version (5.4.32) does not satisfy that requirement.
  Problem 6
    - symfony/config v3.2.6 requires php >=5.5.9 -> your PHP version (5.4.32) does not satisfy that requirement.
    - robmorgan/phinx v0.8.0 requires symfony/config ~2.8|~3.0 -> satisfiable by symfony/config[v3.2.6].
    - Installation request for robmorgan/phinx v0.8.0 -> satisfiable by robmorgan/phinx[v0.8.0].
```

So it seems that the use of the Symfony components by Phinx would bump the PHP requirement to 5.5.9 and higher. Is there something you can do about this requirement (eg, use older versions of the Symfony components) or could it be that the installation guide on your website should just read 'Phinx requires at least PHP 5.5.9 (or later).' in stead?

**Comment by mvrhov** [comment]
The compose.json says 2.8|3.0 so something else is raising your minimum require version.

**Comment by rquadling** [comment]
Check out our Travis builds. PHP 5.4 is quite happily building and passing all tests.

Can you show your `composer.json` file please?

**Comment by Beittil** [comment]
The entirety of my composer.json is basically this:

```
{
    "require": {
        "robmorgan/phinx": "^0.8.0"
    }
}
```

**Comment by mvrhov** [comment]
Well then you are running the composer with php > 5.4

**Comment by rquadling** [comment]
Also make sure your composer is uptodate. `composer self-update`

**Comment by rquadling** [comment]
@mvrhov, did you mean < 5.4?

**Comment by rquadling** [comment]
Hmm. Travis only has the latest version of each minor release of PHP.

**Comment by Beittil** [comment]
@mvrhov The server really does only have 5.4.32 installed, how could it be running >5.4?

@rquadling composer  self-update
You are already using composer version 1.4.1 (stable channel).

This is the output.

**Comment by mvrhov** [comment]
The server yes. What about your local development. I don't know the way you deploy.

**Comment by Beittil** [comment]
Was away for a while, but resuming this.

@mvrhov I fail to see how my local development environment is relevant. Yes, it runs PHP 5.5.9 which picks up installing and migrating with Phinx no problem. But, the server (where I update source with Git), has 5.4.38 and thus, does not.

Since Phinx claims to be 5.4 compatible (see min version required in its composer.json file) and appears not to be my question is: Can Phinx me made compatible again or not?

**Comment by mvrhov** [comment]
The problem is that if you run the composer install/update with 5.5 in local environment, then newer packages can be installed. The problem then becomes in the production if you just copy everything over blindly, or run composer install. as the composer.lock file contains never versions of the packages.

**Comment by Beittil** [comment]
Now that was the missing piece of information :) Thank you @mvrhov!

Solved it by removing composer.lock on the server, running composer install flawlessly and then committed the server's version of composer.lock back to the development environments.

**Comment by Capenus** [comment]
@Beittil you can use the special [platform config setting](https://getcomposer.org/doc/06-config.md#platform) in your `composer.json`. Just set there the PHP-Version of your production server and you are save in the future.
