### ISSUE TITLE
Rollback one migration fails

### ISSUE THREAD

**Issue by moritz-h** [robmorgan/phinx#1059]
Do `phinx rollback` with only one migration fails: `No migrations to rollback`

`phinx rollback -t 0`still works correct for one migration. Also error is the same if I start a new project with only one migration, and try to roll this back or if I have more migration and rolling them back one by one.
Error is in v0.8.0, is working with v0.7.2.

**Comment by rquadling** [comment]
What version order have you got configured?

**Comment by moritz-h** [comment]
I configured nothing, so default version order.

**Comment by piotr-cz** [comment]
This issue is valid for both _creation_ and _execution_ order

**Comment by rquadling** [comment]
Waiting on https://github.com/robmorgan/phinx/pull/1060
