### ISSUE TITLE
As a developer I want to see an error if the connection goes away while executing a query.

### ISSUE THREAD

**Issue by Mondane** [robmorgan/phinx#1078]
I have ran a `$this->query` like:

```php
$this->query("
            ALTER TABLE `shop_customer`
            ADD COLUMN `modified_datetime` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);

            ALTER TABLE `shop_address`
            ADD COLUMN `modified_datetime` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);

            ALTER TABLE `shop_order`
            ADD COLUMN `modified_datetime` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);

            ALTER TABLE `shop_shipment`
            ADD COLUMN `modified_datetime` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);
");
```

On my development environment which holds only a subset of production data and the migration ran without problems. After checking, all alter tables were performed.

When I deployed this migration to my production database. Phinx didn't report an error, but after checking, it turned out not all alter tables were performed. The tables holds several gigabytes of data.

I tried running the remaining alter tables manually and 1 of them took too long and my client reported a timeout. The remaining alter tables weren't performed. This is what must have happened when Phinx performed the migration.

Could the phinx logic be adjusted to check for lost connections and then raise an error so the deployer gets notified when such a situation occurs? Now, it was a mystery why code wasn't working anymore and took a while to figure out not all migrations were performed.

**Comment by rquadling** [comment]
There is an issue within PHP/PDO/mysql. When you execute a batch of queries (like you've done), PDO does not throw an exception if there is an error.

As such Phinx doesn't get told that something went wrong.

The work around is to only execute 1 statement per query.

**Comment by Mondane** [comment]
You mean even http://php.net/manual/en/pdo.errorinfo.php doesn't show that
error?

Op 22 apr. 2017 16:16 schreef "Richard Quadling" <notifications@github.com>:

**Comment by rquadling** [comment]
PDO ErrorInfo will be populated, but only for the statement that caused the error. There's no way to determine from the initial result of the query, which statement failed, not without getting the next result set and then checking ErrorInfo. Add to this the lack of transactional DDL queries, the database cannot restored to a working state.

Whilst I wasn't involved in the initial design, it is certainly one of the reasons to NOT use batched queries for MySQL via PDO.

**Comment by Mondane** [comment]
But, you do get info one of the queries failed? For sake of data integrity,
wouldn't it be better to throw an error so the deployer get's notified and
can check which query went wrong?

Don't get me wrong, I'll use single query statements from now on in Phinx
to avoid this situation.

Op 22 apr. 2017 23:27 schreef "Richard Quadling" <notifications@github.com>:

**Comment by rquadling** [comment]
Maybe we could display the errorinfo, but when would we iterate through the result sets?

In addition, there is only the option to move forward through the sets. No resetting back to the first one having determined that there was an error in the batch.

We also don't have any information available to us to know if the user has finished with the result set.

So much so, we currently do nothing and allow the end user to use appropriate PDO calls to do the switching.

Batch queries allow mixing of DDL, DML, DCL and TCL queries. We can't know when a user has finished with a DDL query explicitly - as they could move backwards and forwards or use a random access for the result set.

So, in essence, for us to know if there was an error in the batch, we have to deny access to the results.

I don't think that's an option either.

I think I'll add a warning to the documentation against using batches of queries. Of course, a user wanting to test the for errors themselves is still available when using batches.
