### ISSUE TITLE
Add custom commands

### ISSUE THREAD

**Issue by johnrobertporter** [robmorgan/phinx#1105]
I'm not sure if this has already been asked, so forgive me if it has.

I have only just stumbled across this package, and I was reading issue #180 about multi tenant systems.

Is there any way to add custom commands, as I think that issue could be solved by making a command that could dynamically swap out configuration to deal with connecting to multiple tenant databases.

I hope there is a way :)

**Comment by robmorgan** [comment]
Hi @johnrobertporter theres no sort of 'plugin' system per say to add custom commands but you can easily fork the project and add your command in the `PhinxApplication.php` file. That issue you mentioned has a number of workarounds and suggestions for dealing with multiple databases. Phinx will eventually support this feature if I receive the desired level of support to work on it. Cheers, Rob

**Comment by johnrobertporter** [comment]
Thanks for your response @robmorgan
