### ISSUE TITLE
Error reporting for create

### ISSUE THREAD

**Issue by michaeljs1990** [robmorgan/phinx#164]
on creating a new migration is wants you to use CamelCase but is really requiring you to use PascalCase

**Comment by robmorgan** [comment]
Closing this - PascalCase is technically correct, however when I present Phinx more people understand camel case.

**Comment by kafoso** [comment]
> Closing this - PascalCase is technically correct, however when I present Phinx more people understand camel case.

But it's wrong... Just because a great number of people fail to educate themselves that doesn't make things acceptable.

**Comment by dereuromark** [comment]
@kafoso Maybe a name that isnt visually clear isn't the best way to describe it then?
CamelCase and camelBacked fit better because they make it crystal clear what is meant. Or would you also know what HenryCase, RobertCase and ElliCase could mean?

**Comment by kafoso** [comment]
PHP class names are Pascal Case (https://techterms.com/definition/pascalcase). Or rather, as per PSR-1 (https://www.php-fig.org/psr/psr-1/), "StudlyCaps".

Camel case should/must always begin with a lowercase letter.

Developers then write the class name in camel case and then get shouted at for not using camel case...

```sh
$ vendor/bin/phinx create sorryWhat
```

```
In Create.php line 169:

  The migration class name "sorryWhat" is invalid. Please use CamelCase format.

```
