### ISSUE TITLE
Method to add table comment

### ISSUE THREAD

**Issue by sooners87** [robmorgan/phinx#175]
DB: postgres
I could not find a method to add table comment. Right now i am executing like this

$this->execute("COMMENT ON TABLE test_table IS 'Contains test data';");

Is there a table method to do this?

**Comment by ng33** [comment]
This is still not working in 0.4.4 with Postgres 9.3.4

**Comment by robmorgan** [comment]
Okay I have implemented table comments for Postgres now. It looks possible for SQLite as well but its a bit of a hack so I ignored it. Definitely possible for SQL Server, but also a lot more complex. I'll create a seperate issue for this if anyone wants it.
