### ISSUE TITLE
Error on init. failed to open stream: phar error: "phinx.yml" is not a file

### ISSUE THREAD

**Issue by philsown** [robmorgan/phinx#183]
I tried installing this as a phar using box. I'm getting this error when I try to init a project.

```bash
$ phinx init .
PHP Warning:  file_get_contents(phar:///usr/local/bin/phinx/src/Phinx/Console/Command/../../../../phinx.yml): failed to open stream: phar error: "phinx.yml" is not a file in phar "/usr/local/bin/phinx" in phar:///usr/local/bin/phinx/src/Phinx/Console/Command/Init.php on line 92
created ./phinx.yml
```

I tried rebuilding the phinx.phar with box, then extracting it. There's no .yml files in the resulting phinx.phar-contents directory.

So, I edited the box.json file and added "phinx.yml" to the "files" section:

```js
     "files": [
         "LICENSE",
         "phinx.yml"
     ],
```

That seemed to fix it. Must be an oversight? I have Phinx version 0.3.0

**Comment by keibro** [comment]
I encountered this issue also - as you noted Rob, it attempts to look for the yml within the phar as opposed to creating it locally/outside of the phar.
