### ISSUE TITLE
Support prepared statements

### ISSUE THREAD

**Issue by hkdobrev** [robmorgan/phinx#203]
PDO has built-in prepared statements.

The adapters in Phinx could easily support them by accepting both an SQL string and an array with input parameters.

This will resolve #132 as well.

**Comment by courtney-miles** [comment]
I just hit this issue on a production environment with a developer who did not escape values that were pulled from the database.

It very difficult to accuse a developer of being negligent, when the package we use offers no convenient way to safely prepare queries and execute them.

This makes Phinx a rather risky product to use.  Phinx encourages the bad practice of concatenating strings to produce a query.

I think it's overdue for Phinx to accommodate best practices by providing a convenient interface for using prepared queries.

**Comment by shadowhand** [comment]
@courtney-miles someone started on this in #256 but it was never finished. If you wanted to use that as a base for a fresh pull request, it would be greatly appreciated.

**Comment by courtney-miles** [comment]
Pull request is in #486.  I didn't know how to link it to this ticket, sorry.

**Comment by robmorgan** [comment]
closing in favour of #486.
