### ISSUE TITLE
Definition of current working directory

### ISSUE THREAD

**Issue by djmattyg007** [robmorgan/phinx#217]
I built Phinx as a phar file using Box and placed it in ~/bin so that I don't have multiple copies of it lying around.

Unfortunately, Phinx appears to get confused about what the current working directory is. Even though in its debugging output it will think it is in the directory I am running it in, all of the commands seem to think the current working directory is the directory the phar file is in (~/bin).

**Comment by robmorgan** [comment]
For me it seems to work fine:

`$ php bin/phinx-v0.4.5-48-gd32cc11.phar migrate -c ./phinx.yml`

**Comment by robmorgan** [comment]
due to the fix in #183.
