### ISSUE TITLE
Change method not working for addForeignKey

### ISSUE THREAD

**Issue by sooners87** [robmorgan/phinx#224]
Phinx 0.3.3. Postgres 9.0.15

On rollback throwing error:

$this->table('table_name')
             ->addColumn('id', 'integer', array('null' => true, 'default' => null, 'comment' => 'identifier'))
             ->addForeignKey('id', 'table_referenced', 'id', array('delete'=>'SET_NULL', 'update' => 'CASCADE'))
             ->update();

Got error:
[PDOException]
  SQLSTATE[42703]: Undefined column: 7 ERROR:  column "referenced_table_schem
  a" does not exist
  LINE 3:                       WHERE REFERENCED_TABLE_SCHEMA = DATABA...

On Rollback also tried only having addForeignKey method.But still got the same error.

**Comment by robmorgan** [comment]
I wasn't able to replicate this. I need to see how you originally created the table as well. Did you disable the automatic primary key column? 

I was able to create two migrations
* One created the two tables
* 2nd migration created an FK between the two

I could then rollback successfully. Closing this for now.

**Comment by irothenbaum** [comment]
Can it not be done in one migration? If not, why not?
