### ISSUE TITLE
[Feature request] MyIsam mimmicked support for delete cascade / set_null / default restrict

### ISSUE THREAD

**Issue by twicejr** [robmorgan/phinx#234]
I'd like to know how you think about adding support for mimicking foreign keys with MyISAM tables using triggers.

Maybe this sounds ridiculous but there are clients missing InnoDB support. Some shared hosters for example. I know there's is a tiny market for it.

Something like:
$this->table('item')
->addForeignKey('category_id', 'categories', 'id', array('myisam' => true));

It should then add a trigger restricting it (nullifying / cascading is less complex)

<?php $trigger = <<<SQL
delimiter

create trigger deleterestrict_{$foreign_table}_{$local_table} before delete on item
for each row
begin
declare msg varchar(255);

select {$foreign_key} from {$foreign_table} where {$foreign_key} = old.{$local_key} limit 1;

//test if any..... todo..
//if so:

set msg = concat('DeleteRestrictError: Trying to delete a restricted record in {$foreign_table}, by items in {$local_table} ', cast(old.{$local_key} as char));
signal sqlstate '45000' set message_text = msg;

delimiter ;
SQL;?>

See also 
http://stackoverflow.com/questions/5342852/how-to-use-delete-cascade-on-mysql-myisam-storage-engine
http://dev.mysql.com/doc/refman/5.1/en/create-trigger.html#c8808

**Comment by robmorgan** [comment]
Closing this until I see further support from the community.
