### ISSUE TITLE
Add command line options w/ db, host, user, pass etc.

### ISSUE THREAD

**Issue by mcd-php** [robmorgan/phinx#241]
My credentials are already in `phing`, in `.ini` files loaded by `-Dsite=instance_name`, and i don't want to duplicate, prepending multiplle `export PHINX_DBUSER=$(remote.db.user)` to any exec call is bad option also.

**Comment by robmorgan** [comment]
Closing this - I've decided for security reasons we won't support user/pass etc via command line params. They are supported in ENV vars and we might add interactive input in the future.
