### ISSUE TITLE
LONGTEXT and TINYINT support

### ISSUE THREAD

**Issue by dancryer** [robmorgan/phinx#249]
Phinx is amazing, and we're just now setting up PHPCI to use it for managing the database, however we'd really like to see support for LONGTEXT and TINYINT columns - as we use both extensively.

If these are not available in all database engines, perhaps in those adapters they could be aliased to TEXT and INT respectively?

**Comment by shadowhand** [comment]
This is now complete. XINT and XTEXT are now fully supported.

**Comment by davidyell** [comment]
How does this work for `tinyint` ?

I've tried the following an ended up with `tinyint(4)` when I wanted `tinyint(1)`

```php
    public function change()
    {
        $table = $this->table('answers');

        $table->changeColumn('correct', 'integer', [
            'length' => 1,
            'default' => null,
            'null' => true,
            'limit' => \Phinx\Db\Adapter\MysqlAdapter::INT_TINY
        ]);

        $table->save();
    }
```

**Comment by dereuromark** [comment]
We might need better docs
```
use Phinx\Db\Adapter\MysqlAdapter;
...
->addColumn('request', 'text', [
    'default' => null,
    'limit' => MysqlAdapter::TEXT_MEDIUM,
    'null' => false,
])
```
also TEXT_LONG etc are available.

**Comment by burzum** [comment]
@dereuromark I would prefer a factory method for columns.

```php
->addColumn($this->column('foo')
    ->default('bar')
    ->null(true)
    ->type(Type::MEDIUM_TEXT));
```

The method could cast it to whatever the DB uses for MEDIUM_TEXT. This could be done in a backward compatible way by accepting a row object or the three args it takes.  This gives us autocomplete in IDEs and an advantage over the messy arrays.
