### ISSUE TITLE
Query retuns PDOStatement instead of array

### ISSUE THREAD

**Issue by Cactucs** [robmorgan/phinx#252]
If I'm using phinx whith MySQL (connected via PDO) and  when I call `$this->query()` it returns PDOStatment instead of array as is said in `MigrationInterface` ([source](https://github.com/robmorgan/phinx/blob/0.3.x-dev/src/Phinx/Migration/MigrationInterface.php#L115-L121)). 

It's because `MysqlAdapter` extends `PdoAdapter` which extends `PDO`. So the `query()` method is called on PDO which returns `PDOStatement` ([docs](http://us2.php.net/manual/en/pdo.query.php)) and not array as said in docs.

**Comment by robmorgan** [comment]
fixed in the docs now.
