### ISSUE TITLE
Drop PHP 5.3 & Possibly PHP 5.4 support

### ISSUE THREAD

**Issue by robmorgan** [robmorgan/phinx#263]
This depends on how many people are still using PHP 5.3. PHP 5.3 is EOL or really near EOL.

**Comment by robmorgan** [comment]
CakePHP 3.x requires at least PHP 5.4.16 or greater. (http://book.cakephp.org/3.0/en/installation.html)

**Comment by w2pc** [comment]
Apps that won't upgrade to 5.4 should have already started a refactor process. Software should never get to EOL terms, especially web applications. People will stay on 5.2 and 5.3 until they are forced to move. I wish all these shared hosting services would force that.

**Comment by jboonstra** [comment]
In the year+ since I last commented, we have been able to move to PHP 5.6. Even if that hadn't happened, though, I would have been totally fine with removing PHP 5.3 support.

**Comment by robmorgan** [comment]
Cool, Good to know!

**Comment by robmorgan** [comment]
FYI - Nearly 90% of users voted to drop PHP 5.3 support in this year's Phinx product survey. Therefore instead of waiting for 2.0.0 I'm going to drop PHP 5.3 support in 0.6.0. At the moment I'm contemplating whether to skip 5.4 also, but we need to take into account dependant projects such as CakePHP.

**Comment by robmorgan** [comment]
https://github.com/cakephp/cakephp/issues/5602

**Comment by robmorgan** [comment]
closing this as we no longer support 5.3. Will open another issue to drop 5.4 later this year.
