### ISSUE TITLE
Document PHP Configuration in "Configuration" Section of Documentation

### ISSUE THREAD

**Issue by andrewmunsell** [robmorgan/phinx#276]
Currently, only the YAML configuration format is documented in the [section of the documentation](http://docs.phinx.org/en/latest/configuration.html) titled "Configuration". However, Phinx supports PHP configuration as documented in the ["Commands" section](http://docs.phinx.org/en/latest/commands.html#configuration-file-parameter).

Documentation on the PHP configuration format should also be included in the "Configuration" section.

**Comment by JeromeGill** [comment]
+1 this is a solid feature as it allows dynamic loading of variables thus safe versioning of the config file. Browsing the source as we speak to work out how it works, but that isn't ideal!

**Comment by robmorgan** [comment]
Closing. Other formats are now documented in `configuration.rst`.
