### ISSUE TITLE
Config flag for prepending timestamp to migration classes to allow duplicate names

### ISSUE THREAD

**Issue by anlutro** [robmorgan/phinx#306]
In cases where an application goes through a lot of changes there can be a lot of back and forth in terms of adding/removing tables, columns, indexes, foreign keys etc. In such cases, not being able to have two migration files named the same can be annoying. I have been in positions where I've had migrations called

- create_something_table / class CreateSomethingTable
- drop_something_table / class DropSomethingTable
- create_something_table_again / class CreateSomethingTableAgain
- drop_something_table_again / class CreateSomethingTableAgain
- create_something_table_thirdtime / class CreateSomethingTableThirdTime

In my eyes, if you know you're going to be in such a position, having at least the possibility to prepend a timestamp to the class name itself in order to simplify the name of the migration itself is useful.

I'd suggest a root config key called `prepend_timestamp` or something, which is a boolean.

**Comment by robmorgan** [comment]
I'm closing this for now until I see further support from the community.
