### ISSUE TITLE
INFO WANTED : Handling views, stored procedures, triggers in Phinx.

### ISSUE THREAD

**Issue by rquadling** [robmorgan/phinx#309]
Hi.

Currently Phinx is pretty good for table orientated migrations. Sure, if your team is working on several different branches with their own migrations, you need to take care if column positioning is important, but there again, a "release manager" role would oversee the integration and hopefully all is good.

But for things like views, stored procedures, triggers, etc., anything that requires SQL code, it is less good.

Does anyone have any process that covers handling migrating of non table related elements?

I have no preference on any particular approach, I just want our developers to have a process that is clearly understood on what to do for migrating these elements.

Regards,

Richard.

**Comment by heskyji** [comment]
We have a lot of stored procedures and functions. At the moment, we just use `execute` function with raw SQL statements for procedure and function definitions. We just have to make sure we captured the old definitions in the `down` function too. The pain point is that it is almost impossible to tell what's changed in the pull request.

**Comment by rquadling** [comment]
WOW! Wasn't even aware I'd opened this issue over 2 years ago. A lot has changed. One change is that I am now a contributor to this project.

So, with that, I'd like to close this issue and direct you to https://github.com/robmorgan/phinx/issues/1046.

I'm looking for opinions, ideas, suggestions, etc. relating to the RFC. Please take a read through and let me know what you all think. The more info I have, the better chance that the end result will be useful to those who need it, rather than just what I think it needs.

Thank you.

**Comment by vegbrasil** [comment]
Hi, I'm sorry to comment on a old/closed issue. But this issue is exactly around my question:

Is using `execute()` still the only way to create views?

Thanks!

**Comment by rquadling** [comment]
@vegbrasil, for the time being it is. I am starting work on repeatables this week (have work level dev time as we need the same functionality). So hopefully in the not too distant future, repeatables will be a 'thing'.
