### ISSUE TITLE
Add Phinx task to Phing

### ISSUE THREAD

**Issue by zuker** [robmorgan/phinx#34]
Phing (http://www.phing.info/) is a great CI tool for PHP, based on Apache Ant, so how about adding Phinx task to Phing as an alternative to DbDeployTask?
http://www.phing.info/docs/guide/trunk/chapters/ExtendingPhing.html

**Comment by robmorgan** [comment]
I'm closing this due to lack of interest. I no longer use Phing, but if anyone else does then they can contribute an unofficial 3rd party plugin.
