### ISSUE TITLE
Cakephp and other legacy applicaitons

### ISSUE THREAD

**Issue by BardiaAfshin** [robmorgan/phinx#340]
On any given legacy application that wants to transition into using Phinx they will be faced with the challenge of 
1. Supporting legacy migrations
2. Not needing to load initial migrations in production, as they have already run ie. You don't want to drop your customers table and add columns to it on production which have already been created by your legacy methods, or any other legacy migration.
3. Need to set the revision in some time in the future , ie phinx set-revision REVISION-NUMBER , this iwll allow the rather collateral collision highlighted in number 2

@robmorgan @community thoughts on this?

**Comment by robmorgan** [comment]
Closing unless I see further support from the community.
