### ISSUE TITLE
when creating a migration, the migration helper can optionally scaffold some helper code for user

### ISSUE THREAD

**Issue by BardiaAfshin** [robmorgan/phinx#346]
when I run
./phinx create CreateUsersTable

It'd be helpful to have the migration created have something like
```php
    public function up()
    {
        $table = $this->table('users');
        $table->create();
    }
```

community thoughts? 

Same thing could go for drop table, add index to table, add column, etc.

**Comment by robmorgan** [comment]
closing for now, I decided to add more docs instead: See 7ae04be8f0c5d7d3a953ce2ba05fb2294dd44149
