### ISSUE TITLE
Possibility to run Phinx in PHP script

### ISSUE THREAD

**Issue by george-oakling** [robmorgan/phinx#364]
Hi! I didn't find any info about running the Phinx directly in my app, something like the below code, which I can insert into my PHP deploy script:

$phinx = new Phinx();
if($phinx->migrate()) {
 // continue deployment, migrate finished without errors
} else {
  echo $phix->errorlog(); // display all errors, stop deployment, etc.
}

**Comment by alexbowers-tecmark** [comment]
Any update on the documentation @shadowhand

**Comment by jmny** [comment]
an migration example : 

https://gist.github.com/jmny/c957de6984c9d939c059

**Comment by topolanekmartin** [comment]
@jmny Thanks a lot for useful example! :)
