### ISSUE TITLE
MySQL adapter cannot set COMMENT on table, only on COLUMN

### ISSUE THREAD

**Issue by george-oakling** [robmorgan/phinx#368]
Hi! I just discovered through the code, that Phinx can set several parameters on table and column creation (collation is perfect btw!). For my backend is needed to set the table comments, which are shown there as table/column names. So i set up Phinx like this:

```
public function change()
	{
		$postsOptions = array(
			"collation" => "utf8_czech_ci",
			"comment" => "AAAA");

		$posts = $this->table("posts", $postsOptions);
	
		$posts
			->addColumn('title', 'string', array('limit' => 40))
			->addColumn('body', 'text', array('comment' => 'Text'))
			->addColumn('created', 'datetime')
			->create();
	
	}
```

Collation is set OK, column comment is set OK, but table comment is not set. Why? The code responsible for this is in MySQL adapter, AFAIK, but the comment is not set...

**Comment by beporter** [comment]
Wasn't this done in #334?

**Comment by george-oakling** [comment]
Hi, sorry for delay, yes, it is working now.
