### ISSUE TITLE
How to Register Custom Adapter

### ISSUE THREAD

**Issue by twilsonxpert** [robmorgan/phinx#388]
I see in the docs the code snippet for registering custom adapters.

http://docs.phinx.org/en/latest/configuration.html#supported-adapters

Question is, where in the world do I put that code?

**Comment by shadowhand** [comment]
I have this fully working now (without docs), but it currently depends on #428. If you want a preview of the changes, [compare it on my fork](https://github.com/shadowhand/phinx/compare/shadowhand:i413-abstract-adapter-wrapper...i413-adapter-factory).

**Comment by shadowhand** [comment]
#439.
