### ISSUE TITLE
PHPStorm Plugin

### ISSUE THREAD

**Issue by saada** [robmorgan/phinx#405]
It would be amazing to have a Phinx plugin for PHPSTORM. I'm willing to work on it if someone is willing to guide me along the way. Thoughts?

**Comment by alexbowers** [comment]
What would this plugin do? Make it so you can run the migration within the program? Because you can already have it done via the built in terminal of phpstorm

**Comment by iammichiel** [comment]
And what would be the benefit of a plugin for PhpStorm?

**Comment by robmorgan** [comment]
Closing this until I see further support from the community.

**Comment by ArtemGoutsoul** [comment]
Would be nice to have a plugin similar in style to the composer UI in phpstorm (Tools menu). With a few simple buttons:
* create environment configurations
* status
* create new migration
* run migration
* roll back migration

This would make the functionality a lot more discoverable and friendlier for beginners.

**Comment by robmorgan** [comment]
This could be provided by a 3rd party lib/repo/plugin. I'm happy to host it, but I would never distribute it with the main Phinx lib.

**Comment by rquadling** [comment]
There has been quite a bit of criticism regarding PHPStorm's lack of use of PHP. Having to write plugins in Java is a pain if you don't know Java. But if you can build a plugin, with enough documentation and a lack of implied knowledge, then others can contribute.
