### ISSUE TITLE
AppVeyor builds are failing for no apparant reason

### ISSUE THREAD

**Issue by shadowhand** [robmorgan/phinx#429]
https://ci.appveyor.com/project/robmorgan/phinx/build/1.0.388

![screen shot 2015-01-01 at 21 33 41](https://cloud.githubusercontent.com/assets/38203/5594073/edcc8dc4-91fd-11e4-9044-713b7831f0a6.png)

Tests are passing, but fail with "The batch file cannot be found".

**Comment by robmorgan** [comment]
ahh now I think I know what broke this.

**Comment by alexbowers** [comment]
@robmorgan Any update on getting this fixed? Quite a few pull-requests are failing due to a build error

**Comment by robmorgan** [comment]
Appveyor is not running the tests at all right now. Looking into it...

**Comment by robmorgan** [comment]
I've narrowed the batch file cannot be found error down to `InitTest.php`.
