### ISSUE TITLE
Allow use of 'identity' in Column options

### ISSUE THREAD

**Issue by temperedvision** [robmorgan/phinx#430]
There have been a few requests/PRs in the past for the use of an auto increment option for columns. Where I feel these has so far failed is that this is very MySQL specific, and a better option (at least from my cursory inspection of the codebase) already exists. The 'setIdentity()' method.

Therefore I would like to see the 'identity' to be added in as an option for Phinx\DB\Table\Column::setOptions() which would set the "auto increment" option for a custom primary key in a way consistent with the automatic primary key options.

eg.
```php
$this->table('my_table', ['id' => false, 'primary_key' => 'custom_id'])
    ->addColumn('custom_id', 'integer', ['signed' => false, 'identity' => true])
    ->create();
```
On a MySQL specific benefit, this would also allow much easier usage of unsigned primary keys, which are more common in existing MySQL databases (which is shown in above example).

**Comment by shadowhand** [comment]
Using options with `identity=true` is [already possible](https://github.com/robmorgan/phinx/blob/47c0514da3f5206dacca58baade3e5885409aaa9/src/Phinx/Db/Table/Column.php#L497-L515) with the syntax you gave. And the `identity` option does trigger `AUTO_INCREMENT` [in the MySQL adapter](https://github.com/robmorgan/phinx/blob/47c0514da3f5206dacca58baade3e5885409aaa9/src/Phinx/Db/Adapter/MysqlAdapter.php#L910).

**Comment by shadowhand** [comment]
I think the confusion here is that `identity` implies primary key, whereas `auto_increment` can be used for columns other than the primary key.

**Comment by temperedvision** [comment]
its not currently possible as the only valid options are as follows:

'limit',
'default',
'null',
'precision',
'scale',
'after',
'update',
'comment',
'signed',
'timezone',
'properties',

**Comment by temperedvision** [comment]
i agree that there may be use cases for using auto increment to non primary key fields, but those are highly dependent on platform support, whereas an enforcement via identity will ensure that this is only applicable to primary keys, and thus supported by all currently supported database engines.

**Comment by shadowhand** [comment]
I did not realize it was disabled as a user option. Fixed! :)

**Comment by temperedvision** [comment]
no worries, nothing like a trial by fire to test out a feature :)
