### ISSUE TITLE
Set Configuration path via TextWrapper

### ISSUE THREAD

**Issue by alexbowers** [robmorgan/phinx#433]
I have been trying to find a way to set the configuration path (the phinx.yml location) via the TextWrapper but so far have come up empty. Any ideas how this can be done?

@shadowhand

**Comment by shadowhand** [comment]
Currently not possible because you can't inject options directly into TextWrapper. Best thing to do would be to replace `$default_env` with `array $options` in the `__construct` to allow overloading options.

**Comment by shadowhand** [comment]
Closed because question is answered, but certainly reference this issue if you make a PR.

**Comment by alexbowers** [comment]
The problem I see is that environments and so on can be set after migration, but configuration has to be set before

IE. via command line it is

phinx -c "name" migrate -e default

Or is this a non-issue?

**Comment by alexbowers** [comment]
@shadowhand I have created a pull request. Please could you look it over?

**Comment by alexbowers** [comment]
Example Code Usage:
```php
<?php
	$app = new \Phinx\Console\PhinxApplication();
	$wrap = new \Phinx\Wrapper\TextWrapper($app, array(
                'config_path' => '../phinx.yml',
                'parser' => 'yaml'
        ));
	$test = $wrap->getMigrate();

	print_r($test);
```

It works without the second parameter. 
Either, all or none of the param values are required and can be passed. parser is an assumed value based on extension of the config_path, default config path is ./phinx.yml, Also, you can pass through the environment.
