### ISSUE TITLE
Support for larger BLOB types in MySQL

### ISSUE THREAD

**Issue by bretrzaun** [robmorgan/phinx#45]
With the current mapping of the binary type to use the "BLOB" type in MySQL restricts the column to 64KB of data.
Is there a way to use the other blob types "mediumblob" or "longblob" ?

**Comment by mamchenkov** [comment]
Is there any hope for this to be fixed any time soon?  :smile:  
With Phinx being used by other projects now (like CakePHP 3) it starts to get in a way of a lot of things.

**Comment by mamchenkov** [comment]
This can be closed now, I guess.
