### ISSUE TITLE
Versioning of the tool

### ISSUE THREAD

**Issue by mcapodacqua** [robmorgan/phinx#456]
I'm adding this issue because I had some questions about your versioning strategy.
I realized that you use to fix some bug that breaks BC, but you don't implement any tag after that, I would expect a patch version of the app, otherwise we will have the fix of the bug in a dev branch, and I don't think is a good idea to put a dev branch in my composer definition right? (I think all of us agree here).
For example, I opened #425 , it was fixed by babe492 , and this commit exists on branch 0.4.x-dev. So, to use this fix, I have to wait for the new release or use the dev branch in my composer file.
The main question here is, do you think is good to follow the [Semantic Version](http://semver.org/) standard here?
The basic idea is:
>Given a version number MAJOR.MINOR.PATCH, increment the:
>
>MAJOR version when you make incompatible API changes,
>MINOR version when you add functionality in a backwards-compatible manner, and
>PATCH version when you make backwards-compatible bug fixes.

For my example, you will need to change the PATCH number after the fix.

Can some of you guys add an explanation of the tagging strategy here? I think is something good to be discussed.

**Comment by shadowhand** [comment]
@mcapodacqua I agree with you on all points, and agree that semver is a sane strategy. Up until this point, I had left @robmorgan in control of tags. From now on, I will be more diligent about making point releases for bug fixes.

**Comment by shadowhand** [comment]
@robmorgan I've tagged 0.4.2, can you update the website please?

**Comment by robmorgan** [comment]
@shadowhand For your reference I've also made a Wiki page outlining the steps I take: https://github.com/robmorgan/phinx/wiki/Releasing-a-new-version-of-Phinx

**Comment by shadowhand** [comment]
Thanks @robmorgan, I was able to update the website and docs using the wiki
instructions!
