### ISSUE TITLE
Duplicate Names

### ISSUE THREAD

**Issue by daniel-lang** [robmorgan/phinx#473]
When creating a second migrations with the same name. Like `phinx create Test`  and running the same command again will work. But commans like `status` will output an error: 
```
[InvalidArgumentException]
Migration "20150205104723_test.php" has the same name as "20150130090329_test.php"
```

A check when creating the migrations would be great.

**Comment by shadowhand** [comment]
Duplicate of #362.

**Comment by daniel-lang** [comment]
#362 is about duplicate timestamps when creating two migrations at once. I'm addressing the problem of creating a second migration with the same name.

In my opinion, these are two different problems.

**Comment by robmorgan** [comment]
@daniel-lang they are indeed two different problems.
