### ISSUE TITLE
Update the docs website

### ISSUE THREAD

**Issue by alexbowers** [robmorgan/phinx#478]
docs.phinx.org is massively out of date. Can we get that updated to use the latest docs?

**Comment by shadowhand** [comment]
Done! And a fresh release 0.4.2.1 made to ensure that all the necessary stuff (website, docs, composer) all reflect the current version.

**Comment by alexbowers** [comment]
Thanks. Thats great.

**Comment by robmorgan** [comment]
@shadowhand if your doing releases be sure to follow the http://semver.org/ guidelines. E.g: 3 components for a version instead of 4.
I would of done `0.4.3`.

**Comment by shadowhand** [comment]
@robmorgan sorry, it seemed silly to use 0.4.3 when there were no functional changes. I thought semver had allowance for "hotfix" points, but it seems not. Future releases will follow accurately.

**Comment by robmorgan** [comment]
@shadowhand yeah sure! I've always followed the X.Y.Z but I've normally grouped several commits into a release and only updated the Y (minor) when I thought it was really necessary.
