### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by alexbowers** [robmorgan/phinx#479]
Do we have a roadmap anywhere of features for 4.3 etc?

**Comment by ameech** [comment]
:+1:

**Comment by robmorgan** [comment]
will be managed here: https://github.com/robmorgan/phinx/wiki/Roadmap

**Comment by alexbowers** [comment]
@robmorgan Is it not useful to have an issue for tracking comments and thoughts on the roadmap?

**Comment by robmorgan** [comment]
@alexbowers I suppose we could comment on the overall direction of the Roadmap here, but right now most features have their own issue + lengthy discussion.
