### ISSUE TITLE
Postgres: Syntax Error

### ISSUE THREAD

**Issue by daniel-lang** [robmorgan/phinx#480]
I noticed a couple of problems with the changeColumn method of the PostgresAdapter:
* Changing the default doesn't work since this has to be done with a separate `ALTER TABLE` just like changing the NULL constraint
* Replacing the `NULL` and `NOT NULL` with an empty string in the getColumnSqlDefinition function doesn't work when specifying the DEFAULT value since it is not the end of the query

**Comment by m1ome** [comment]
:+1:

**Comment by shadowhand** [comment]
Fixed by #481
