### ISSUE TITLE
Support for BIGSERIAL and JSONB in PGSQL Adaptor

### ISSUE THREAD

**Issue by jwoodcock** [robmorgan/phinx#482]
Right now I've found no support for BIGSERIAL nor JSONB in the PGSQL adaptor. 

I've tested out a fix locally and will be submitting a PR with it once I make sure to have not messed up test coverage.

**Comment by tacman** [comment]
Can you post your fix or your fork of the repo?  The ability to use jsonb  would be enormously helpful.

**Comment by jwoodcock** [comment]
@tacman You can see all the code changes here:
https://github.com/robmorgan/phinx/pull/483

I just ran out of time and couldn't make the changes they asked. In addition, we've ran into a number of other limitations that has forced us to use only the exec/query commands.

**Comment by robmorgan** [comment]
Closing this for now, please open a separate issue for `BIGSERIAL` and I'll merge if I see further support from the community.
