### ISSUE TITLE
Boolean fields are not showing up as unsigned in MySQL

### ISSUE THREAD

**Issue by amfriedman** [robmorgan/phinx#490]
Given this method call...

```php
$table->addColumn('is_visible', 'boolean', array('length'=>1, 'signed' => false))
```

The column that is created in mysql shows type TINYINT(1) but remains signed, so it is ignoring my 'signed'=>false flag. Expected behavior is that it respects the flag at minimum, and even makes unsigned be the default state for boolean fields. 

The best solution, of course, is to improve the MySQL adaptor's code to translate this "boolean" type to "bit" in MySQL.

**Comment by alexbowers** [comment]
http://docs.phinx.org/en/latest/migrations.html#valid-column-options Boolean isn't listed as accepting the signed flag.
