### ISSUE TITLE
addIndex() should allow for naming of the index

### ISSUE THREAD

**Issue by amfriedman** [robmorgan/phinx#491]
It is common practice for a developer to specify unique names for table indexes, (eg, "idx_widget_colors"). It'd be great if addIndex() would accept a 'name' argument to allow for this practice.

**Comment by coatesap** [comment]
@amfriedman - It looks like the index name can be set as part of the options parameter. For instance, this works for me:

    $this->table('payments')->addIndex('createdAt', ['name' => 'payments_createdAt'])->save();

**Comment by daverogers** [comment]
Confirmed @coatesap. This issue can be closed.
