### ISSUE TITLE
Limit option not being honoured for integers

### ISSUE THREAD

**Issue by martinbean** [robmorgan/phinx#493]
I’m trying to create integers of a specific length, but it seems the `limit` (and `length` alias) options are not being honoured. For example:

```php
$table = $this->table('foo');
$table->addColumn('bar', 'integer', ['limit' => 10]);
$table->save();
```

When I run this migration, it’ll actually create an `INT` column with a limit of 11 (the default). The `limit` option in the migration has no effect.

I’ve narrowed this down to https://github.com/robmorgan/phinx/blob/0.4.x-dev/src/Phinx/Db/Adapter/MysqlAdapter.php#L761. In my case, the column is being parsed as an integer correctly, but because my `limit` value isn’t greater or equals to the `INT_TINY` constant value (255), it’s just returning the default of `11` (hello, Spinal Tap).

Is this correct? I’ve never seen an `INT` column in a MySQL table with a limit of 255. Or am I doing something completely wrong?

**Comment by battlecow** [comment]
+1

**Comment by jeesus** [comment]
What if I need to use it along with `MysqlAdapter::INT_TINY` when creating tables? I believe the column specific type should use some other key as it is not working atm. Creating the table and then immediately changing it wouldn't be too efficient, would it?
