### ISSUE TITLE
Allow explicit integer size

### ISSUE THREAD

**Issue by naquad** [robmorgan/phinx#501]
`int(4)` - can't be done with Phinx, please add `size` / `length` to `integer`

**Comment by shadowhand** [comment]
Isn't this a duplicate of #493?

**Comment by naquad** [comment]
I've tried with `limit`:

```
->addColumn('opacity', 'integer', array('null' => true, 'limit' => 3))
```

result:

```
`opacity` int(11) DEFAULT NULL,
```

**Comment by shadowhand** [comment]
Yes that is the same as #493.

**Comment by naquad** [comment]
Any hint on when will that be released?

**Comment by shadowhand** [comment]
Just released v0.4.3! https://phinx.org/

**Comment by naquad** [comment]
Thank you! That fixed the problem.

**Comment by zdenekgebauer** [comment]
there is also small bug with length of signed/unsigned columns, ie:
->addColumn('bar_id', 'integer', array('limit' => MysqlAdapter::INT_REGULAR, 'signed' => false))
create
`bar_id` int(11) unsigned NOT NULL,
but it should create 
`bar_id` int(10) unsigned NOT NULL,
