### ISSUE TITLE
[Feature Request] AddIndex should support Index limit

### ISSUE THREAD

**Issue by daniel-aranda** [robmorgan/phinx#518]
There is no support for index [limits](http://dev.mysql.com/doc/refman/5.0/en/create-index.html) limit. 

Imagine that you have a field named "href" which is TEXT, then you want to create on index of it, you need to set a limit, let's say 50 chars, so ideally you want to add the index like this:

Expected:
```php
->addIndex(['href'], ['limit' => 50])
```

Currently not supported. Thank You.

**Comment by khayyam90** [comment]
Hum, so I'm not the only one looking for this feature.
This feature would be greatly appreciated.

**Comment by marias-truelogic** [comment]
+1 This is a big turn off.

**Comment by clthck** [comment]
I want to implement this feature specifically. What am I gonna do to get assigned this issue?

**Comment by robmorgan** [comment]
I wasn't aware MySQL indexes support limits?

**Comment by daniel-aranda** [comment]
@robmorgan imagine this use case:

You have a field named "html" that is VARCHAR with limit of 1000 chars. 

Now you want to create an index on it. Technically it is not possible because the limit of a MySQL index is 255(for InnoDB to say something).

So, you could create an index on that column, but just using the first 255 chars of the column(you use limit on the index to specify it). 

So the partial index is created. There are use cases where this is really helpful.

**Comment by robmorgan** [comment]
@daniel-aranda ok thx now I understand. happy to accept your proposal then. will accept a PR or i'll code it in 0.5.2.

**Comment by antonienko** [comment]
@robmorgan I would like to contribute the PR for this issue. Since I'm not familiar with the codebase (I just used the project but never had a look deeply at the codebase), can you point me to a starting point where I can start digging in order to implement this feature?

**Comment by robmorgan** [comment]
fixed in 4872101b8c99e72515b9e8766b094bbbcbdd054f

**Comment by daniel-aranda** [comment]
Sweet! Thank You @antonienko @robmorgan
