### ISSUE TITLE
Ability to set a default migration template file

### ISSUE THREAD

**Issue by acoulton** [robmorgan/phinx#528]
There doesn't seem to be a phinx.yml option for a default template file for new migrations. We want to customise our migration template as standard but it looks like the only way to do that is to pass `--template` every time.

I propose adding a `migration_template` option to phinx.yml, and using that in [AbstractCommand::getMigrationTemplateFilename](https://github.com/robmorgan/phinx/blob/0.4.x-dev/src/Phinx/Console/Command/AbstractCommand.php#L298).

If you'd accept that I can work up a PR and attempt to add a test (it doesn't look like there are any existing tests for CreateCommand so it may be tricky).

**Comment by sabl0r** [comment]
+1

**Comment by RQuadling** [comment]
+1

**Comment by Stene3** [comment]
+1

**Comment by PalliDotCom** [comment]
+1

**Comment by rquadling** [comment]
If you intend to build a PR for this, I would recommend also supporting the ```--class``` alternative.

Currently, you cannot use ```--template``` and ```--class```, so I would also inhibit the use of both of these entries in the configuration file.

**Comment by robmorgan** [comment]
closing as I merged 100f0188b1cf5342bb3bbc402ea88c859e5dda3b
