### ISSUE TITLE
How to create fulltext index?

### ISSUE THREAD

**Issue by tomasstrejcek** [robmorgan/phinx#533]
Hi, is there any way to create fulltext index on columns? (for now we are using alter table query)
Nothing in source code hints it could be done.
eg
```
$table->addIndex($cls, ['type'=>'fulltext'])
```
creates only standard INDEX-

Thanks

**Comment by alexbowers-tecmark** [comment]
+1

**Comment by zdenekgebauer** [comment]
+1

**Comment by sergeyklay** [comment]
+1

**Comment by shopblocks** [comment]
Any update on this?

**Comment by robmorgan** [comment]
scheduled for next release.

**Comment by shopblocks** [comment]
Thanks.

**Comment by gauravmak** [comment]
+1

**Comment by robmorgan** [comment]
0.5.2 will add support for MySQL initially.

**Comment by robmorgan** [comment]
If you are not using at least MySQL 5.6 you will need to force the `MyISAM` engine type. e.g:

```
$table = $this->table('table1', ['engine' => 'MyISAM']);
$table->addColumn('email', 'string')
      ->addIndex('email', ['type' => 'fulltext'])
      ->save();
```
