### ISSUE TITLE
Unable to rollback

### ISSUE THREAD

**Issue by rbalik** [robmorgan/phinx#538]
I'm getting this error message when I attempt to rollback my last migration:

[PDOException]                                                                      
SQLSTATE[42000]: Syntax error or access violation: 1090 You can't delete all columns
 with ALTER TABLE; use DROP TABLE instead                                           

This is my change() function:

```
        $usergroups = $this->table('usergroups');
        $usergroups->addColumn('name', 'string',
            array('length'=>32, 'default'=>''))
            ->addColumn('key', 'string', array('length'=>32))
            ->addColumn('newusersonly', 'boolean',
                array('default'=>false))
            ->save();
        $usertogroup = $this->table('user_to_group',
            array('id'=>false, 'primary_key'=>array('userid', 'groupid')));
        $usertogroup->addColumn('userid', 'integer')
            ->addColumn('groupid', 'integer')
            ->save();
        $plansdata = $this->table('plansdata');
        $plansdata->addColumn('groupid', 'integer',
            array('default'=>0))
            ->update();
```

**Comment by alexbowers** [comment]
A table requires columns, if you're trying to remove all columns as part of your down() method, you should use dropTable() instead.

http://docs.phinx.org/en/latest/migrations.html?highlight=droptable

**Comment by rbalik** [comment]
I understand that, but I figured the whole point of the change() function was that it would figure that out on it's own. If you're creating a table the first time around, shouldn't it drop it when you rollback?

**Comment by rbalik** [comment]
Oh, I just reread the docs and saw that I need to use create() instead of save(). I'll make that change.
