### ISSUE TITLE
Possibility of including a 'name' column in phinxlog

### ISSUE THREAD

**Issue by coatesap** [robmorgan/phinx#543]
One change that would make life easier when working on a project with lots of branches and migrations would be to include the name of the migration in the phinxlog table.

I appreciate that in an ideal world we'd always remember to rollback any migrations relating to a branch of code before switching branches, but in a busy development environment, this isn't always realistic!

This results in often spending a fair bit of time trying to track down which branch contains a migration which is still "up" but missing:
![List of missing migrations](http://i57.tinypic.com/e16r9y.png)
If this list gave away at least a migration name, it would make tracking them down much easier.

I'd be happy to provide a PR for this enhancement if meets approval.

**Comment by RQuadling** [comment]
+1

**Comment by bravo-kernel** [comment]
:+1:

**Comment by lorenzo** [comment]
:+1:

**Comment by robmorgan** [comment]
switching release versions

**Comment by coatesap** [comment]
Hi @robmorgan, it looks like this has some support, so to get things kick-started, could you outline what the rough pattern is for adding a column to Phinx's own log table? Does Phinx have it's own internal migration facility?

**Comment by rquadling** [comment]
Migrating the phinxlog table would be useful for the breakpoint mechanism we use. Currently it is via column sniffing, which isn't ideal.

**Comment by bravo-kernel** [comment]
@coatesap the columns are created here https://github.com/robmorgan/phinx/blob/73a2a9ff121e58f3c9a715a69471dadfe74b38b5/src/Phinx/Db/Adapter/PdoAdapter.php#L425

**Comment by rquadling** [comment]
@bravo-kernel Take a look at https://github.com/rquadling/phinx/blob/feature/BreakpointSupport/src/Phinx/Db/Adapter/PdoAdapter.php#L185, if you want to add a column to an existing phinxlog table, you have to sniff to see if it exists as there is no migration support for phinxlog itself from within phinx - which is a migration utility. I can certainly see that the phinxlog table is probably not going to receive a lot of migrations, so maybe sniffing is the best option at the moment.

**Comment by robmorgan** [comment]
yes we will have to sniff in order to ensure backwards compatibility. Unfortunately this also means running an extra query on every connection, but we'll have to live with it until I can remove it in a later release.

**Comment by robmorgan** [comment]
So far my proposal keeps the red background for the missing migration:

![screenshot 2016-02-29 18 13 03](https://cloud.githubusercontent.com/assets/178939/13402371/33756016-df10-11e5-95ee-0d904134818a.png)

I'm still debating if this is the best approach.

**Comment by bravo-kernel** [comment]
Looks more than helpful to me.

**Comment by coatesap** [comment]
We've been using our fork based on #744 for some time now in our team without any issues, so let me know if any other changes are required in order to get this merged.

**Comment by robmorgan** [comment]
@coatesap thanks! it turns out the implementation I've written is almost identical to yours. I completely missed it.. I've thrown mine away and just merged yours. Cheers, Rob.

**Comment by bravo-kernel** [comment]
Awesome job :clap:
