### ISSUE TITLE
Add primary key to Phinx log tables

### ISSUE THREAD

**Issue by reloaded** [robmorgan/phinx#544]
I think it makes perfect sense to mark the `version` column in the Phinx log as the PRIMARY KEY. I run MySQL in strict mode and MySQL doesn't like tables without primary keys.

I'm more than happy to work on a PR if enough people want this.

**Comment by rbalik** [comment]
Would definitely like this. Somebody else opened an issue already though: #247

**Comment by reloaded** [comment]
Oh, I didn't see that one! Thanks.

**Comment by robmorgan** [comment]
fixed in 602aac4e23bacd5115e67db89b81bdfb855d305c
