### ISSUE TITLE
Using phinx programmatically

### ISSUE THREAD

**Issue by sergeylukin** [robmorgan/phinx#548]
Hi,

I'd like to run Phinx commands from my PHP scripts. I've looked into source code and extracted what I thought essential from Phinx\Console namespace and here is what I've got working so far (assuming script is placed in same directory as configuration file):

```php
<?php

use Symfony\Component\Console\Output\StreamOutput;
use Phinx\Config\Config;
use Phinx\Migration\Manager;

$Phinx = new Manager(
  new Config(require __DIR__ . '/phinx.php', __DIR__),
  new StreamOutput(fopen('php://memory', 'a', false))
);
$Phinx->migrate('ENVIRONMENT_NAME');
$Phinx->rollback('ENVIRONMENT_NAME');
```

Am I on right track? Thanks

**Comment by vnen** [comment]
The simple web interface in this repo seems to do something like what you want: https://github.com/robmorgan/phinx/blob/0.4.x-dev/app/web.php

It uses the [`Phinx\Wrapper\TextWrapper`](https://github.com/robmorgan/phinx/blob/0.4.x-dev/src/Phinx/Wrapper/TextWrapper.php) class, which wraps the Phinx commands in methods.

**Comment by sergeylukin** [comment]
That indeed looks pretty much like what I was looking for. Thank you!

**Comment by fracz** [comment]
```
$app = new PhinxApplication();
$app->run(new StringInput("migrate"), new ConsoleOutput());
```

**Comment by Stalinko** [comment]
```
function runMigrations()
{
    $app = new Phinx\Console\PhinxApplication();
    $wrap = new Phinx\Wrapper\TextWrapper($app);

    $wrap->setOption('configuration', '/path/to/config');
    $wrap->getMigrate();
    return $wrap->getExitCode() === 0;
}
```
