### ISSUE TITLE
Request for a new release

### ISSUE THREAD

**Issue by constantinoschristoforou** [robmorgan/phinx#568]
Hi there

Cakephp3 is using 0.4.2 version of phinx library but i need some features of 0.4.x-dev branch( LONG BLOB types etc), is it possible to create a new release in order the cakephp use the latest features?

Thanks

**Comment by robmorgan** [comment]
fixed in b4b7d1e045d679278d4cb9ab18fd513f15f4797e

**Comment by constantinoschristoforou** [comment]
Thanks @robmorgan
