### ISSUE TITLE
don't have fine grained control of running migrations

### ISSUE THREAD

**Issue by dmead** [robmorgan/phinx#573]
is it possible in phinx to have a simple "up one" or "down one" command? it seems like the version specific flags make this possible, but not out of the box.

**Comment by rquadling** [comment]
Issuing a rollback without a target will rollback 1 migration. No equivalent for migrating forward 1 step.

You can rollback/migrate to a target, or if you use my fork, you can set a breakpoint that will stop rollbacks at a point if you use a target of 0 (i.e. rollback everything).

I switch between branches of the projects that I work on, each will have its own migrations, but the develop branch's migrations, I don't want to interfere with, so a breakpoint is perfect for this.

**Comment by dmead** [comment]
like an actual debugger breakpoint?

**Comment by rquadling** [comment]
Not like a debugger, no. Our master branch contains migrations that are in production, so we don't want developers in their own feature branches amending their DB by rolling back the migrations beyond that which is live. So, by setting the breakpoint when in the master branch, the migrations are protected when in a branch, allowing further development to take place, and during testing, ```phinx rollback -e development -t 0``` can be used to reset the db to that of the production environment. You can add a ```--force``` attribute to bypass the breakpoint.

If you do force a migration past the breakpoint, the entry in phinxlog is lost and so is the breakpoint.

**Comment by dmead** [comment]
ahhh interesting. i'll have a look

**Comment by daniel-gomes-sociomantic** [comment]
interesting stuff indeed, might help us as we have the same scenario (master has live production/migrations, feature branches have new code/migrations, and we need to be able to switch branches at any time). I was thinking of trying to `phinx rollback -e development` as many times as there are new migrations on the feature branch (when comparing to master) to ensure that branch's migrations are all rollbacked, but the "breakpoint" feature is interesting too. 

Can you explain how to use it in your fork? How do you set the endpoint?

**Comment by rquadling** [comment]
If you are using composer, then add the following to your ```composer.json``` the following repository (amend to fit your own setup) ...

```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/RQuadling/phinx"
        }
    ]
```

Then you can do a ```composer update``` to get my branch. You will also have 2 other differences (```phinx status -v``` support and a bug fix regarding template/class in config/commandline).

Then ```phinx breakpoint --help``` should provide all you need.

Please add a note to https://github.com/robmorgan/phinx/issues/494 https://github.com/robmorgan/phinx/pull/497 if you like this. Or contact me for more info.

**Comment by rquadling** [comment]
Oh. You'll also need to use ```"robmorgan/phinx": "dev-0.4.x-dev",``` as your version.

**Comment by rquadling** [comment]
I regularly rebase so this is always uptodate with upstream bug fixes and the like.

**Comment by robmorgan** [comment]
@rquadling this can be closed as breakpoints are now merged?

**Comment by rquadling** [comment]
I'd say yes. Both in terms of functionality and a lack of response from the OP.
