### ISSUE TITLE
Sync the online docs

### ISSUE THREAD

**Issue by IngwiePhoenix** [robmorgan/phinx#582]
I just revisited this project due to a friend's notice, and realized that the contents of docs.phinx.org and the `docs/` folder are not the same, especially when it comes to creating tables and such.

Could you possibly update the online docs?

**Comment by elliotwms** [comment]
What branch are you looking at? As far as I know the documentation online is the latest stable release (0.4.x) whereas the latest stuff on GitHub is on the development branch (0.4.x@dev)

**Comment by robmorgan** [comment]
Hi @IngwiePhoenix the docs are built off `master` and yes the changes in `0.4.x-dev` need to be merged. That has now been done and will automatically update shortly.

**Comment by IngwiePhoenix** [comment]
Yeah I was reffering to the default branch seen on Github. I usually dont touch the branch selector mostly because it tends to point at a currently working version.
