### ISSUE TITLE
Add precision and scale support for Postgres numeric data type

### ISSUE THREAD

**Issue by kyrozetera** [robmorgan/phinx#589]
There is currently a `TODO` comment for this in the Postgres adapter. This will help me clean up many of my migrations where I am forced to use `$this->execute($query)` with raw sql.

**Comment by kyrozetera** [comment]
Just realized that limit can be a stringy value, (e.g. `['limit' => '10, 2']`). That being said, using precision and scale is a bit more clear.

**Comment by Garbee** [comment]
Should this be closed since the PR was merged?
