### ISSUE TITLE
Any possibility to implement Seeders?

### ISSUE THREAD

**Issue by daison12006013** [robmorgan/phinx#591]
Hi @robmorgan,

Are not you planning to add a seeder capabilities? If ever you want to have some seeders then, I might be able to contribute in your package.

As of now, I'm creating a re-structured phalcon framework (https://github.com/phalconslayer/slayer), and I am using your phinx to make migrations.

While I am still looking for some packages that supports seeders like Laravel.

**Comment by elliotwms** [comment]
I'm pretty sure something like this is on the roadmap, but for now it's simple enough to roll your own seeders into the provided functions, even leveraging something like [faker](https://github.com/fzaninotto/Faker)

**Comment by robmorgan** [comment]
Hi,

The seed command is a top prio and will be shipped in Phinx 0.5.0 - the next major release. I'm just working on support for all adapters at the moment.

Regards,

Rob

**Comment by daison12006013** [comment]
@robmorgan, I hope you could provide a way for us to re-use a class or an interface that could override the entire process, and provide a factory to use something like faker.

If you'll be importing this in the migration part, I think it is much better to provide a class for other purpose.

**Comment by robmorgan** [comment]
@daison12006013 I didn't implement a factory, but I've made it pretty easy to integrate Faker. I'll publish a blog post with 0.5.0.

**Comment by robmorgan** [comment]
Closing, please refer to #172.
