### ISSUE TITLE
Redshift Adapter

### ISSUE THREAD

**Issue by kyrozetera** [robmorgan/phinx#592]
It would be great to add in support for Redshift. Currently it is possible using the Postgres adapter, but it is missing certain capabilities and there are occasional syntax differences requiring much use of raw SQL execution to create tables.

To implement, it would mostly be an extension of the Postgres adapter, removing some support, and adding support for things like `DISTKEY` and `SORTKEY` during table creation.

If this is something others would like to have, I would be happy to build out the new adapter.

**Comment by robmorgan** [comment]
Yes I agree if this is something other people want, we can add Redshift support. Hopefully its as easy as extending the Postgres adapter. That would be cool!
