### ISSUE TITLE
[NFR] some really usefull methods

### ISSUE THREAD

**Issue by salarmehr** [robmorgan/phinx#594]
(I am not sure if the current version has any stuff to the following methods or not)

Adding the following methods can empower Phinx even more:

~~~~~
$tables=$this->getTables();
foreach($tables as $table){
   $table->dump('/backups/myDb/'.$table->getName.'.sql');
   $table->changeEngine('innodb')->convertCharset('utlf8_general_ci')->resetAutoIncrement();
}

**Comment by robmorgan** [comment]
1. Phinx won't do data exporting, other tools are better suited for this.
2. I will support the utility methods if I see more support from the community

**Comment by woodsae** [comment]
Hey Rob, I agree with @salarmehr that these could be quite helpful.  I'm thinking of a situation where you might want to back up a table to specified location (e.g. file, S3) in your `up()` function, and restore the table from that backup file in your `down()` function.

We are currently looking into using Phinx in our project and having this functionality would be quite helpful.
