### ISSUE TITLE
[NFR] Some shorthand functions

### ISSUE THREAD

**Issue by salarmehr** [robmorgan/phinx#595]
Following mysql syntaxes: `drop if exists`, `create or replace` , etc, having some utility functions for the following code is really helpful:

~~~~
if ($userTable->hasColumn('uDate')) {
            $userTable->changeColumn('uDate', 'timestamp',
                ['default' => 'CURRENT_TIMESTAMP']);
        }
else{
 $userTable->addColumn('uDate', 'timestamp',
                ['default' => 'CURRENT_TIMESTAMP']);
}
~~~~
Can be as simple as:
~~~~
$userTable->addOrChangeColumn('uDate', 'timestamp',
                ['default' => 'CURRENT_TIMESTAMP']);
~~~~~

I can send a push request I you will merge it.

**Comment by elliotwms** [comment]
Your migrations should be building on the migrations before it. If the column doesn't exist before it then it is probably indicative of another problem.

Your database should be in a particular state that Phinx expects before you migrate

**Comment by salarmehr** [comment]
Our application is not developed with Phinx in mind. So there are lot of inconsistent schema for various customers. I think an option named for example modifyColumn is really useful to create a column if it does not exist.

**Comment by w2pc** [comment]
This idea totally goes against the whole reason of using migrations. You could write a migration to create/drop a column and run that before your other migration. You don't want to blindly be creating or dropping columns. You want to know specifically when that action took place.

**Comment by salarmehr** [comment]
@w2pc  Phinx already has some methods to handle unknown status: `hasColumn`, `hasIndex` , … . I only requested some shorthand utility functions. If you think there are not useful for you, you can simply ignore them.

**Comment by robmorgan** [comment]
Closing this for now until I see further community support.
