### ISSUE TITLE
Config::replaceTokens() should have type hint

### ISSUE THREAD

**Issue by t1gor** [robmorgan/phinx#603]
Code reference: https://github.com/robmorgan/phinx/blob/0.4.x-dev/src/Phinx/Config/Config.php#L251

The `replaceTokens()` function is only being called from `__construct()`, which has type hint for `array $config`, which is then being passed to `parseTokens()`.

Somehow, if the submitted argument is not an array, the `parseTokens()` function will simply return the argument without any processing. It makes even less sense as `__construct()` is type-hinted and nothing other then array can't be passed. 

In my opinion, type-hint should be introduced there and then simply a call to `recurseArrayForTokens($arr, $tokens);` will be returned each time.

I will submit the pull-request shortly with some other tests for Config class.

**Comment by robmorgan** [comment]
fixed in 825bc94f5c5bb28087461debdf5043410a09fa55
