### ISSUE TITLE
Target/migrate to a point in time

### ISSUE THREAD

**Issue by stoiev** [robmorgan/phinx#613]
Since migrations are timestamped (and it seens GMT timestamped), I would suggest the possibility to run migrations up to/down to a specific point in time.

It's not an alternative to migrate/rollback. It's a *goto* migration.

It would be specially useful for automatized deployments (Continuous Integrations).

Rollbacks and new releases could be managed with just one parametrized command, whatever how many migrations/rollbacks exist on the way, and without concerning to know a specific target. 

Example:
```bash
$ phinx status
Phinx by Rob Morgan - https://phinx.org. version 0.4.4

using config file ./phinx.php
using config parser php
using migration path migrations

 Status  Migration ID    Migration Name 
-----------------------------------------
     up  20150713195818  CreateMatchOnline
   down  20150714211140  AlterTimedRankingBaseTable
   down  20150730150436  AddMainMenuOption
```
Then I could:
```
$ phinx goto 20150714211141
Phinx by Rob Morgan - https://phinx.org. version 0.4.4

using config file ./phinx.php
using config parser php
using migration path migrations
using adapter mysql
using database los8escalones

 == 20150714211140 AlterTimedRankingBaseTable: migrating
 == 20150714211140 AlterTimedRankingBaseTable: migrated 0.1189s

All Done. Took 0.1189s
```

If there it's possible/desirable, I could work on a PR for it.

**Comment by rquadling** [comment]
There is a ```--target|-t``` parameter for both migrate and rollback. It would look like ```goto``` could be simulated by ```phinx rollback -t nnn && phinx migraet -t nnn```. Maybe.

**Comment by rquadling** [comment]
OOI, I have a PR https://github.com/robmorgan/phinx/pull/497 allowing you to set a breakpoint which will stop rollbacks from going beyond (unless forced). We use this to help developers keep their local DB in step with the develop branch when they are developing in a feature branch.

**Comment by stoiev** [comment]
Hi @rquadling 

It could be simulated by actual commands as you said, but the user (or automated process) has to know if it is a rollback or a migration, and needs to know a valid target string. Avoid those necessities is the reason of this issue.

It's possible to archive this outside phinx, comparing the desirable timestamp with directory migration's list and retrieving migration status. I will need something like this to my deployments (I'm building installable RedHat RPM's, and considering to add migrations during package installation/upgrade/downgrade), but I will wait some feedback before PR merge possibility before try to touch phinx code.

I think your PR is more development process centric. If I got it correct, it could be overlap by a PR for this issue on terms of functionality. Could you confirm it?

Best Regards

**Comment by rquadling** [comment]
Oh!

The tail of my ```phinx status``` is ...

```
     up  20150716153209  AddStatusToViewItemsExtended
     up  20150721120501  StaffSalesCutoffAfterSessionStart
     up  20150721125945  PaymentChannelNames
     up  20150723091830  CreateKentsCavernBundledItemsCategory
     up  20150723095141  OrderLineIndex
     up  20150730112201  UnredeemedTicketsReportPermissions
```

If I run ```vendor\bin\phinx migrate -t 20150721125945 -e development```, this performs a rollback such that the tail of my status is now ...

```
     up  20150716153209  AddStatusToViewItemsExtended
     up  20150721120501  StaffSalesCutoffAfterSessionStart
     up  20150721125945  PaymentChannelNames
   down  20150723091830  CreateKentsCavernBundledItemsCategory
   down  20150723095141  OrderLineIndex
   down  20150730112201  UnredeemedTicketsReportPermissions
```

So it would seem that ```migrate -t``` === ```goto -t```!

**Comment by rquadling** [comment]
And if, from the new position, run ```vendor\bin\phinx migrate -t 20150723095141  -e development```, I'm left with 1 migration to go, again confirming to me that migrate with a target is equivalent of a goto with a target.

**Comment by stoiev** [comment]
Thanks, man! You just saved me.

I could not find this comportment explicit exposed on [docs](http://docs.phinx.org/en/latest/commands.html#the-migrate-command), but I can suppose that probably will remain stable.

I can rewrite the issue suggesting only an optional modifier (more back compatible scenario), to consider target as a 'point in time'. With this modifier, even when target is not valid, phinx will decide to migrate/rollback to the near previous/next migration.

It can be something?

**Comment by stoiev** [comment]
#624 implements this on a proper way
