### ISSUE TITLE
phinxlog table

### ISSUE THREAD

**Issue by lwrbakro** [robmorgan/phinx#618]
I cannot find the default_migration_table structure or a command to create it.

is there any command? Or specification?

**Comment by rquadling** [comment]
It is produced when you run a migration.

The creator is in ```\Phinx\Db\Adapter\PdoAdapter::createSchemaTable()```.

This is called as part of ```\Phinx\Db\Adapter\PdoAdapter::setConnection```

**Comment by rquadling** [comment]
One downside is that if you want to add additional data to the phinx log (I do for my breakpoints), you do have to sort of hack it. A migration would have been nice to have.

**Comment by lwrbakro** [comment]
My first migrations executes only SQL CREATE TABLE commands from file:
```php
public function up() {
    $this->execute('DROP DATABASE `myapp`');

    $this->execute('CREATE DATABASE IF NOT EXISTS `myapp` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci; USE `myapp`;');

    $this->execute(file_get_contents('database.sql'));
}
```

During the ```phinx migrate``` command I get the following error:


```
 [PDOException]                                                               
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'myapp.phinxlog'   
  doesn't exist
```

Could the error's caouse be that I don't use the 
```php
$users = $this->table('users');
$users->addColumn('username', 'string', array('limit' => 20))
   ...
    ->save();
```

**Comment by lwrbakro** [comment]
.

**Comment by rquadling** [comment]
The error is that you drop the database.

Bye bye phinxLog.

**Comment by lwrbakro** [comment]
OK

I see the problem is on my computer. I will make a workaround by truncating by php commands.

Maybe it could be a good feature/enhancement to handle this type of error: not by showing a command line error, but automatically create the phinxlog table (like in init)

ps: Thanks for the help

**Comment by robmorgan** [comment]
I think if your going to drop your DB and recreate it, then you should call `createSchemaTable()` manually. I'd prefer not to make Phinx too clever.

**Comment by BallisticPain** [comment]
@robmorgan 
Could you put this somewhere into the documentation? I had to dig into this issue to see what your solution is to this. I have no issue calling that method as I do drop my database in my initial migration to get us started using migrations.

**Comment by BallisticPain** [comment]
@robmorgan I really should just write a PR for the documentation. I'll attempt to go that route. Thanks for all your hard work!

**Comment by BallisticPain** [comment]
Also for anyone that stops in here looking for the answer it's more like `$this->getAdapter()->createDatabaseSchema();`.

**Comment by robmorgan** [comment]
The new changes to the phinxlog table are deigned to be automatic. We are basically adding a column if it doesn't already exist.

I'm not going to update the docs as I'm hoping this change is forward compatible with our 1000s of users.

Cheers,

Rob

**Comment by BallisticPain** [comment]
@robmorgan 

I meant documenting the ability to call createSchemaTable. I drop my database because it's the easiest way to get this first migration written as we already have existing tables with key constraints and such.

I'm not concerned with the table itself. I have to after dropping the database re-initialize it for phinx... that's all I was intending. Sorry if this was unclear.

Thanks,
Jarvis

**Comment by robmorgan** [comment]
@BallisticPain hmmmm Phinx is supposed to automatically create the schema table if it doesn't exist. Can you show me an example of how you drop and recreate the db?

**Comment by rquadling** [comment]
https://github.com/robmorgan/phinx/issues/618#issuecomment-128341831

**Comment by BallisticPain** [comment]
@robmorgan 
Similar to the example @rquadling pointed to... here's mine...
```
        // Need to remove all tables first so it can create the new structure...
        $this->dropDatabase('airnav');
        $this->createDatabase('airnav', []);
        $this->execute('use airnav');
        // Create log table
        $this->getAdapter()->createSchemaTable();
```

Thanks!
Jarvis

**Comment by robmorgan** [comment]
ok makes sense i'll put something in.

**Comment by danielonodje** [comment]
![image](https://user-images.githubusercontent.com/1595272/32707727-36e28d36-c826-11e7-908a-eea7511a247d.png)

Still getting this error. Not clear what I should do here. 
Tried calling `$this->getAdapter()->createSchemaTable();` at the start of the change method. no difference.

Running this on freshly created database.
