### ISSUE TITLE
The migrate command fails with the message InvalidArgumentException: The "date" option does not exist

### ISSUE THREAD

**Issue by tejuprasad** [robmorgan/phinx#632]
Hi - 
I upgraded to version 0.4.5.

Running 
`cake migrations migrate`
now gives me a date argument related error.

Rolling back to version 0.4.4, everything works fine.

<img width="777" alt="screenshot 2015-09-01 23 10 11" src="https://cloud.githubusercontent.com/assets/372688/9624167/d8ead6b6-50fe-11e5-86cf-60034422685d.png">

**Comment by HavokInspiration** [comment]
@tejuprasad The issue lies within the CakePHP wrapper. There is a pull request up to fix it : https://github.com/cakephp/migrations/pull/118

**Comment by tejuprasad** [comment]
Thank you.

**Comment by HavokInspiration** [comment]
@tejuprasad The fix has been merged and a release tag was created.
@robmorgan This can be closed.

**Comment by robmorgan** [comment]
cool!
