### ISSUE TITLE
MysqlAdapter->describeTable() and hasTable() don't work when using "connection"

### ISSUE THREAD

**Issue by MasonM** [robmorgan/phinx#645]
These methods depend on the "name" option being set: https://github.com/robmorgan/phinx/blob/0.4.x-dev/src/Phinx/Db/Adapter/MysqlAdapter.php#L1095

However, the "name" option won't be set if your configuration passes in a PDO connection via the "connection" option, as suggested in the docs (http://docs.phinx.org/en/latest/configuration.html).

When that's the case, both describeTable() and hasTable() will return false, since `$options['name']` will be an empty string, which means the queries will have `WHERE table_schema = ''`

**Comment by Sigill** [comment]
Actually, [the documentation](http://docs.phinx.org/en/latest/commands.html#configuration-file-parameter) warns you about the importance of defining the "name" parameter when using the "connection" one to pass a PDO instance.

**Comment by robmorgan** [comment]
I'm closing this, you must also specify `name` as the PDO object has no method for us to access the DB name. It is a PHP limitation.
