### ISSUE TITLE
Table prefixes

### ISSUE THREAD

**Issue by oligriffiths** [robmorgan/phinx#65]
Hi

It would be really useful to be able to use table prefixes in table names. For example:

    $this->table('#__posts');

or

    $this->query('SELECT * FROM #__posts');

And have the #__ be replaced by a constant defined in the config. This is especially needed for applications like joomla who allow for a table prefix to be used to allow interoperability of different applications on the same database.

Oli

**Comment by robmorgan** [comment]
this is now integrated, more info: http://docs.phinx.org/en/latest/configuration.html?highlight=suffix#table-prefix-and-suffix
