### ISSUE TITLE
Add support for native yaml extension

### ISSUE THREAD

**Issue by koenpunt** [robmorgan/phinx#652]
In all of my projects I use yaml for configuration files, and therefore I use the native yaml parser, which is way faster than the PHP implementation, according to my (not so scientific) comparison: https://github.com/koenpunt/yaml-php-benchmark.

And so it would be nice if the yaml parser implementation would be abstracted, so that it is interchangeable

**Comment by robmorgan** [comment]
Hi @koenpunt, I'm closing this for the following reasons:

1. Phinx is a cmd-line and whilst performance is critical, its not as critical as say your application server code for instant.
2. Most PHP users don't have the Yaml pecl extension installed.
3. Adding support for this extension is another thing we have to worry about testing.
4. Native JSON support is built into PHP and may end up being the default config mechanism moving forwards (ala Composer). Yaml would then be optional in this case.

Rob

**Comment by rquadling** [comment]
@robmorgan Please be aware of the almost never ending request to have comments in config files (for Composer and others), something that JSON does not support. And why I and others have been suggesting YAML as the proposed format for commented configuration files.

**Comment by koenpunt** [comment]
> Phinx is a cmd-line and whilst performance is critical, its not as critical as say your application server code for instant.
Sure, but having inconsistency in parsing could lead to problems. And because I'm using that same yaml file to connect to the database, I shouldn't be possible that the interpretation of this file is different because of the parser. (although I haven't seen seen actual differences with the parser, the dump function of the symfony yaml package is absolutely horrible, so I expect there to be issues in the parser as well)

> Most PHP users don't have the Yaml pecl extension installed.
What does make you think so? I don't have statistics either, but I think this isn't really a valid argument.

> Adding support for this extension is another thing we have to worry about testing.
It's still YAML parsing, so if they follow the spec, it should work. The actual testing of the features of the parser is the responsibility of the package itself.

> Native JSON support is built into PHP and may end up being the default config mechanism moving forwards (ala Composer). Yaml would then be optional in this case.
If it becomes optional, why not make the parser itself configurable too?

Anyways, I didn't actually used Phinx yet, but I'll see if I can write up some adapter like interface for configuration parsers.
