### ISSUE TITLE
How to prime a database with migration

### ISSUE THREAD

**Issue by jamespsterling** [robmorgan/phinx#656]
I've got an initial migration that sets up my schema, and I'd like to prime my database with my base set of content. How can I go about doing this?

**Comment by coatesap** [comment]
Hi James, you're probably looking for "seeding" - see http://docs.phinx.org/en/latest/seeding.html.

**Comment by jamespsterling** [comment]
@coatesap thanks!

**Comment by robmorgan** [comment]
Thanks Andrew!
