### ISSUE TITLE
Conventions to migration names – why and how?

### ISSUE THREAD

**Issue by TrogWarZ** [robmorgan/phinx#660]
```
[root@virtualbox]-[/var/www/myprojectdir]-[git feature/phinx]
# phinx create v133
Phinx by Rob Morgan - https://phinx.org. version 0.4.6

using config file ./phinx.yml
using config parser yaml
using migration path /var/www/myprojectdir/migrations



  [InvalidArgumentException]
  The migration class name "v133" is invalid. Please use CamelCase format.



create [-c|--configuration CONFIGURATION] [-p|--parser PARSER] [-t|--template TEMPLATE] [-l|--class CLASS] [--] <name>
```

What's wrong? How can i start and use my application versioning with Phinx?

**Comment by robmorgan** [comment]
Hi Roman,

You can't. You must use CamelCase notation when creating your migrations. 

Try Version133 instead. It may work but I'm not in front of my computer. 

Alternatively read the docs for more information.

Regards,

Rob

**Comment by TrogWarZ** [comment]
@robmorgan , ah, okay, thank you, that was my bad. "V133" works fine. I was suprised when "versionApp133" triggers same error.
