### ISSUE TITLE
Adding a binary 36 column

### ISSUE THREAD

**Issue by jamesdb** [robmorgan/phinx#674]
I am trying to create a BINARY(36) column, code below shows how i am creating the table.

```php
$this->table('articles')
         ->setOptions([
             'charset'   => 'utf8mb4',
             'collation' => 'utf8mb4_unicode_ci',
             'id'        => false
         ])
         ->addColumn('uuid', 'binary', ['limit' => 36])
         ->addColumn('title', 'string', ['limit' => 255])
         ->create();
```

Upon inspecting the table the datatype is being set to BLOB and not BINARY(36) as i expect, am i missing something here?

The reason why i am not using the uuid type is because i don't want to store it as a CHAR.

Nice library by the way.

**Comment by merlindiavova** [comment]
+1

**Comment by jamesdb** [comment]
Closing this issue as solved in v5.
