### ISSUE TITLE
Seeders

### ISSUE THREAD

**Issue by IngwiePhoenix** [robmorgan/phinx#679]
I know, this is for 0.5.x - but I wanted to ask about the current status since it hasnt been mentioned in a long time, including int he commits, as far as i can tell.

Would be nice to know the current state. :) I am a bit over the place since I migrated to Laravel and I want to decide which migrating system to use...

**Comment by rolies106** [comment]
:+1: for this, I'm also looking for this feature, at least maybe I could try some basic feature, I already using phinx for my migration so it would be great if there is some kind of beta version of this data seed feature.

**Comment by robmorgan** [comment]
I was considering some aspects of a more comprehensive version e.g: see #610 for an example. However I'm now more inclined to ship something simpler than maintains BC and avoids changing the behaviour of the existing commands. I'll push something very soon.

**Comment by SacWebDeveloper** [comment]
+1 I would be happy with an implementation very similar to Laravel's. Perhaps it should just be an option on ```phinx migrate``` named ```--seed```.

**Comment by robmorgan** [comment]
My version is similar to Laravel's but not identical. You cannot invoke other seeders from within a seeder.

**Comment by robmorgan** [comment]
Closing in favour of #172
