### ISSUE TITLE
Is there a way to not run all commands in a transaction

### ISSUE THREAD

**Issue by kidbrax** [robmorgan/phinx#688]
ALTER TYPE in PostgreSQL cannot be run inside a transaction so it would be nice if there was a switch to disable transactions for certain migrations.

**Comment by robmorgan** [comment]
@kidbrax at the moment theres not, however here is a workaround you could use:

```
$this->getAdapter()->commitTransaction();
// code to alter type
$this->getAdapter()->beginTransaction();
```

This ends the current open transaction, and then opens another one to keep Phinx happy.
