### ISSUE TITLE
Unable to create fulltext index type

### ISSUE THREAD

**Issue by Eksilente** [robmorgan/phinx#705]
Sample code

$table = $this->table('lastnames');
        $table
            ->addColumn('lastname', 'string', ['limit'=>240,'null'=>false])
            ->addIndex('lastname',['name'=>'lastname','type'=>'FULLTEXT'])
            ->create();

This will only create an index with index type.

**Comment by robmorgan** [comment]
hi @Eksilente. This is actually a feature request. Phinx doesn't support 'FULLTEXT' indexes out of the box. We only support unique and normal indexes. Track the feature here: https://github.com/robmorgan/phinx/issues/533.
