### ISSUE TITLE
Combine suitable changes

### ISSUE THREAD

**Issue by stephenorr** [robmorgan/phinx#708]
We've recently started using Phinx in production, and one of the things I've spotted is that, where all changes in a migration are related to the same table, it does not combine them into a single query.

For my specific example, we are using MySQL, and are adding a new column to a table and then adding a foreign key linking that column to another table. This is being executed as two separate queries, which (because of the massive amount of data we have in that table) is taking rather a long time.

I'm not sure if this is a desired feature, but I intend to see if I can implement the functionality myself, and will submit a pull request once I'm ready :smile:

**Comment by robmorgan** [comment]
@stephenorr hi Stephen, I understand your frustration, but combing queries is probably a very difficult problem to engineer especially when it comes to edge cases. If you know you have a long running query you'd like to optimise I'd recommend use the `query` and `execute` methods for writing raw SQL. 

Anyway best of luck if you decide to have a crack at it!
