### ISSUE TITLE
 php vendor/bin/phinx init outputs shell script

### ISSUE THREAD

**Issue by wwallace** [robmorgan/phinx#726]
I'm not quite sure why the docs tell you to run this bash script as a PHP script. It seems like an error in the documentation. Simply running  ```vendor/bin/phinx init .``` will suffice.

**Comment by robmorgan** [comment]
@wwallace what operating system are you using?

**Comment by rquadling** [comment]
Yeah, ``vendor/bin/phinx`` is for unix/mac/linux, ``vendor/bin/phinx.bat`` is for Windows. Neither can be launched via PHP, both are shell script.

**Comment by wwallace** [comment]
Running Ubuntu 14.0.4. 
@rquadling is speaking the truth here.

**Comment by rquadling** [comment]
And both are created by composer as part of the installation of Phinx.

**Comment by wwallace** [comment]
PR merged https://github.com/robmorgan/phinx/pull/727
