### ISSUE TITLE
method hasIndex returns false always for composit index

### ISSUE THREAD

**Issue by minhaj-resgef** [robmorgan/phinx#728]
indexes created with,
ALTER TABLE `my_table` ADD CONSTRAINT sampleindex UNIQUE (field1,field2)

now inside a migrations 'up' method,
$Table = $this->table('my_table');
$Table->hasIndex('sampleindex');// returns false

**Comment by chrisatsc** [comment]
Try using hasIndexByName('sampleindex') instead.

**Comment by wandersonwhcr** [comment]
MySQL?

**Comment by minhaj-resgef** [comment]
Yeah

**Comment by wandersonwhcr** [comment]
UTSL, method `hasIndex` must receive columns, not the name of the index.

So, `$Table->hasIndex(['field1', 'field2'])` should work.

**Comment by chrisatsc** [comment]
Yeah I'm sorry for bad info; I should've looked closer :(

hasIndexByName is an adapter method, so you have to run it on the table's adapter.

```
$table = $this->table('my_table');
$exists = $table->getAdapter()->hasIndexByName($table->getName(), 'my_index_name');
```

**Comment by cottton** [comment]
I run into the exact same thing.
Its confusing. Perhaps `hasIndex` should throw an **exception** like ~"**column not found**" or similar.

Then you 1st cannot accidentally provide an index name and 2nd cannot accidentally provide non-existing columns (f.e on typo).

Thanks,
/cottton
