### ISSUE TITLE
"Call to undefined method XXXMigration::insert()", does this method really exist ?

### ISSUE THREAD

**Issue by panique** [robmorgan/phinx#749]
Hi, thanks for an excellent project! When trying to fill some data into tables like described in the tutorial / documentation, I stuck on this: The insert()-method doesn't exist inside $this:

**To reproduce** (this is an exact copy minus the down() method of official documentation code from [here](http://docs.phinx.org/en/latest/migrations.html#executing-queries)):

```
<?php

use Phinx\Migration\AbstractMigration;

class NewStatus extends AbstractMigration
{
    public function up()
    {
        // inserting only one row
        $singleRow = [
            'id'    => 1,
            'name'  => 'In Progress'
        ]

        $table = $this->table('status');
        $table->insert($singleRow);
        $table->saveData();

        // inserting multiple rows
        $rows = [
            [
              'id'    => 2,
              'name'  => 'Stopped'
            ],
            [
              'id'    => 3,
              'name'  => 'Queued'
            ]
        ];

        // this is a handy shortcut
        $this->insert('status', $rows);
    }
}
```

The IDE will show that $this->insert() does not exist as a method, running the migration (in an existing table) will throw a fatal PHP error:

*PHP Fatal error:  Call to undefined method NewStatus::insert()*

Can somebody reproduce ? Has anybody an idea what's happening here ?

**Comment by rquadling** [comment]
Almost 100% documentation failure.

**Comment by arlaneenalra** [comment]
I was just bit by this ... Any idea when it will be available?

**Comment by rquadling** [comment]
Unless there is significant changes to the migration class and it has a default table to work with, I can't see this "shortcut" being available any time soon. Of course, that could all change when you make the pull request with the feature matching the documentation! :smile:, but I think correcting the documentation is a better idea.

**Comment by arlaneenalra** [comment]
I don't see why it would.  Unless I'm mistaken, it should be as simple as the #761.  At least that appears to work for me locally.

**Comment by rquadling** [comment]
Oh. Can you add update()/delete() too! :smiley:

**Comment by arlaneenalra** [comment]
That's going to be a bit more difficult. The insert method already existed for the Seed functionality.  To do an update/delete would require going back to the adapters and add query building for the appropriate SQL and then pipe it through Adapater->Table->AbstractMigration.  Plus you need a mechanism to define Where clauses and all the other fun references that update/delete can do (joins anyone?).

If I were going to do it, I'd want to pull in DBAL and use their QueryBuilder to generate the SQL, but that would be pretty fundamental.

**Comment by rquadling** [comment]
I hadn't realised ``insert`` was already present without ``update`` and ``delete``.

**Comment by arlaneenalra** [comment]
Here's the pipeline from AbstractSeed all the way back to the adapter:

https://github.com/robmorgan/phinx/blob/0.5.x-dev/src/Phinx/Seed/AbstractSeed.php#L157-L167
https://github.com/robmorgan/phinx/blob/0.5.x-dev/src/Phinx/Db/Table.php#L571-L594
https://github.com/robmorgan/phinx/blob/0.5.x-dev/src/Phinx/Db/Table.php#L637-L647
https://github.com/robmorgan/phinx/blob/0.5.x-dev/src/Phinx/Db/Adapter/PdoAdapter.php#L330-L350

(I wouldn't have called it easy without that ;)

**Comment by robmorgan** [comment]
fixed in 05fc80b04b9e0e34759651d4276c4d2faa475667. Shipping in the next release. update() / delete() need to be added later.

**Comment by panique** [comment]
Thanks Rob! :+1:

**Comment by gurpreet2501** [comment]
I am unable to push migrations on my production website. @robmorgan  Please suggest me something,. Unable to find the procedure in the documentation. Completed all the necessary steps. Configuration in phinx.yml file is all cool. how to run these on production php website. I am using codeignitor framwork. Thanks

**Comment by robmorgan** [comment]
hi @gurpreet2501 is your problem strictly related to use of the Phinx `insert()` method?

**Comment by gurpreet2501** [comment]
No dear. Locally all the migrations are running fine. Now i have to move the code to production environment. I have to execute some direct url online to run all these migrations or something else needs to be done.

**Comment by robmorgan** [comment]
@gurpreet2501 okay if your still having problems then please open a new issue and describe the problem there in more detail as your problem is not related to this issue (#749).

**Comment by gurpreet2501** [comment]
OK.... thanks
