### ISSUE TITLE
How to declare tinyint(1)

### ISSUE THREAD

**Issue by omer-sds** [robmorgan/phinx#764]
Hi i am trying to create a column with type tinyint and limit 1 using the following but cant get to create a column with limit 1, it always defaults to 4 

```
->addColumn('AppleMusic', 'integer', array('limit'=>  \Phinx\Db\Adapter\MysqlAdapter::INT_TINY ))
```

and if i try the integer with limit 1 like below
```
->addColumn('AppleMusic', 'integer', array('limit'=> 1))
```
it keeps the type integer and sets limit 1 

any link to the documentation although i searched a lot, or similar example would be helpful 
regards,
Omer Aslam

**Comment by omer-sds** [comment]
i need to declare the column type boolean and limit =1 and it will automatically set it to tinyint(1)
regards,
Omer Aslam

**Comment by elita001** [comment]
Hi! Try to use boolean type. It is the same as TINYINT(1):
`->addColumn('AppleMusic', 'boolean')`

**Comment by dereuromark** [comment]
Tip: run dump and check the lock file
The output reveals sth like

    tinyinteger";s:6:"length";i:2;s:8:"unsigned"

which I think makes clear what you are looking for.

Docs here can probably be improved a bit.
