### ISSUE TITLE
create Field of bit(1)

### ISSUE THREAD

**Issue by omer-sds** [robmorgan/phinx#766]
Hi there i cant find any thing in the documentation for declaring columns of type bit (1) or i overlooked the documentation.

Regards,
Omer Aslam

**Comment by lucien144** [comment]
@omer-sds Use the `boolean` type, that does what you want.

**Comment by iijak** [comment]
The `boolean` type sets type of `TINYINT (1)`.
So, that does not what he want.

For a boolean values `BIT(1)` is pretty common.
`BIT (1)` should only allow 0 and 1
`TINYINT (1)` allows any value that can be stored in a single byte, -128..127 or 0..255 depending on whether or not it's unsigned (the 1 shows that you intend to only use a single digit, but it does not prevent you from storing a larger value)

**Comment by omer-sds** [comment]
@iijak damn right you are
