### ISSUE TITLE
What do people think of using Doctrine/DBAL for Phinx?

### ISSUE THREAD

**Issue by rquadling** [robmorgan/phinx#787]
Hi.

Recently started using Doctrine/DBAL for our main project with a view to move relevant parts to the full ORM. But one thing we have already gained is a decent DBAL for our mySQL and MSSQL servers.

What do you feel about replacing the Phinx's DBAL layer with Doctrine/DBAL?

**Comment by mvrhov** [comment]
What would be the gain?
Also the ORM more trouble than it's worth. Switching to pomm in next project as our primary db is postgresql.

**Comment by rquadling** [comment]
One significant gain is that you can use the same DBAL for your main code and your migrations.

I'm not saying using the ORM. At this stage, I'm not sure how ORM and Phinx would play together (just started using Doctrine/DBAL, so no ORM knowledge yet).

By allowing Phinx to handle the migration/rollback and the reversible methods logic, the actual sql can be all constructed from the dbal, and I can use the same dbal in my code.

I suppose, I can just use up()/down() and ignore Phinx's change() and use my DBAL of choice.

**Comment by mvrhov** [comment]
Well the DBAL also has it's own Schema manager, but that forces you to use the DBALs types. Which I at least personally don't like.

**Comment by rquadling** [comment]
Slow merges... oh yes!!!

We are still learning about Doctrine (we have to support mysql and mssql at the moment, so it made sense for us)

**Comment by robmorgan** [comment]
The Doctrine guys have long considered deprecating their migration system and have reviewed a few alternative systems. I worked a few years ago on better integration with Phinx + Doctrine but it didn't really go anywhere. I decided it would be a 'nice to have' if people can use DBAL inside their migrations, but I wasn't going change the core system and add another dependency.

Phinx is also not far from being a light-weight ORM itself. In fact I unofficially use it in this capacity on a few projects.

For relevant discussions please see:

- https://github.com/doctrine/dbal/issues/1816
- #219 - Write a Doctrine DBAL Adapter

There are also a few demo repositories floating around on GitHub.

**Comment by rquadling** [comment]
@robmorgan Thanks for that. Like I said, I've just started using Doctrine's DBAL and got real benefit already.

From quickly reading through those posts, one issue that stands out is the lack of a diff tool in Phinx to generate migrations (similar to RedGate's DBCompare tools).

But having said that, sticking with Phinx for Phinx (we build our migrations first, rather than edit tables - so the diff tool for us is not required). And use DBAL for our code.

I'm happy to close this as there does seem to be enough out there that suggests it has been thought about.
