### ISSUE TITLE
Migration status commands returns 0 when there is down migrations 

### ISSUE THREAD

**Issue by marquesSB** [robmorgan/phinx#796]
ive got the following output with phinx status -e production
Phinx by Rob Morgan - https://phinx.org. version 0.5.0

using config file ./phinx.yml
using config parser yaml
using migration path /home/releases/8ef1a1c76f65446fa312dcefe76e603823667931/database/migrations/radius
using seed path /home/releases/8ef1a1c76f65446fa312dcefe76e603823667931/database/migrations/radius/seeds
using environment production

 Status  Migration ID    Migration Name
     up  20151215143030  PincodeLimitFromDb
   down  20160218084907  LiteReports

and the exit status on this command is 0 -> 
echo $? 
0

in the documentation says that in this case it must return a 1 but it does not

**Comment by daniel-gomes** [comment]
@marquesSB the exit status of the `status` command was only fixed in phinx 0.5.1, as per the [release notes](https://github.com/robmorgan/phinx#version-history)
