### ISSUE TITLE
Missing 'before' option in addColumn?

### ISSUE THREAD

**Issue by davidyell** [robmorgan/phinx#814]
**Use-case**
I need to add a primaryKey to a join table, as I'm storing extra data in there now.

**Options**
There seems to be an option for adding columns `after` other columns, but no way to add a column to the 'beginning' of the table. Equivalent to MySQL `FIRST`.

**Sidestep**
I'll use `execute($sql)`, but I thought it was worth mentioning in case it had been missed, or there was a better sidestep someone could suggest.

**Comment by berarma** [comment]
+1
