### ISSUE TITLE
Foreign Key Auto-Generated Name Too Long

### ISSUE THREAD

**Issue by jmbeekman** [robmorgan/phinx#823]
Sent Rob an email about this, and then decided this was probably a better place.

We have a table with a very long name (60 characters). When Phinx, or PDO as I'm not 100% sure where the error actually is, tries to generate a name for the foreign key constraint it violates the 64 character limit of PDO and I get this:

`
[PDOException]                                                                                      
  SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'very_long_table_name_ibfk_1' is too long   
`

The **_ibfk_1** is apparently added automatically, somewhere. We have custom names defined, **fk_abbvt1_stuff** but are apparently not usable in Phinx currently.

**Comment by odan** [comment]
Currently I'm struggling with a similar issue. I need to set the contraint name manually for a automatic migration generator and to prevent duplicate constraints. 

> InnoDB would rename a user-defined foreign key constraint containing the string “ibfk” in its name, > resulting in a duplicate constraint."

I think there should be a new option for example 'name' to define a custom contraint name.

```php
$table = $this->table('mytable');
->addForeignKey(user_id', 'user', 'id', array('name'=> 'fk_mytable_user_user_id'))
->save();
```
