### ISSUE TITLE
Does not work with SQL loaded from file

### ISSUE THREAD

**Issue by zorobabel** [robmorgan/phinx#832]
I am doing this:

```php
class Init extends AbstractMigration
{
    public function change()
    {
        $path = dirname(dirname(__FILE__)) . DS . 'data' . DS . 'sakila-schema.sql';
        $schemaSql = FileHelper::getFileContents($path);

        $this->execute($schemaSql);
    }
}
```
The console output just says: 

> All Done.

Then, I go to check the db and nothing was created!

I am trying to do a migration for _`Sakila`_ database:

[http://downloads.mysql.com/docs/sakila-db.zip](http://downloads.mysql.com/docs/sakila-db.zip)

I think because the file has a lot of SQL code because I tested the same method with small files and it worked.

Any idea?

**Comment by rquadling** [comment]
How do you make your code reversible in a single statement?

**Comment by rquadling** [comment]
I have extended Phinx to provide me with classes ByDirection and ByDirectory - their templates and base class create a directory for me to put either an up/down SQL file or files in alpha order in an up/down directory. Each file is executed one at a time. This approach may help you.

**Comment by zorobabel** [comment]
@rquadling Thx, I'll take your advice.
