### ISSUE TITLE
Change Primary Key Constraint

### ISSUE THREAD

**Issue by travy** [robmorgan/phinx#842]
Is there a way to change the primary key constraint in phinx without dropping the table?  In other-words, lets say you have a table that uses the default primary_key of 'id' and later on you realized that it would be better to change the primary key.  Is there a way to do so without manually inserting all entries into a new table, dropping the old one and then renaming the new table.

I didn't notice any means for doing this within the documentation and have already tried the following techniques:

1)  Change on table call

```
$assetsDocuments = $this->table('assets_documents', [
    'id' => false,
    'primary_key' => [
        'asset_id', 'document_id'
    ]
])->save();  //  I've also tried with update
```

2)  Dropping the id column

```
//  fails obviously do to constraint, was just a blind attempt
$assetsDocuments->removeColumn('id')->update();
```

3)  Calling addPrimaryKey(array)

```
//  This doesn't seem to do anything on SQL Server 2008
$assetsDocumets->addPrimaryKey(['asset_id', 'document_id'])->update();
```

I'm early in in the development process so I was fine with just dropping the table and creating a new one with the correct primary_key values but I thought this might be a useful feature to have, if not already available.  Or good to have in the docs if it is possible.

**Comment by MikeVelazcoMtz** [comment]
I've never used this utility, but I think that it would help you to read this [http://stackoverflow.com/questions/2111291/remove-primary-key-in-mysql](http://stackoverflow.com/questions/2111291/remove-primary-key-in-mysql):

**Comment by rquadling** [comment]
Note that for mysql with an InnoDB table, a clustered index determines the physical row ordering. In essence/general, the order of the rows is controlled by the primary index, or by various rules if a primary index does not exist.

Changing the primary key has to involve a physical reconstruction of the table.

https://dev.mysql.com/doc/refman/5.5/en/innodb-index-types.html

**Comment by travy** [comment]
Ok that makes sense.  I suppose the only way for this to work in a tool such as this would be to create a table, run a SQL statement re-inserting all data, delete the previous table and rename the new one.

I'll close the ticket.
