### ISSUE TITLE
Would an adapter for ElasticSearch be possible?

### ISSUE THREAD

**Issue by hgraca** [robmorgan/phinx#849]
Im considering making an adapter for Elasticsearch, so we can update the indexes as fast as possible and in an automated way. 
Although ES doesnt work with SQL, it seems that theoretically we would just need to create an adapter for it... But I dont know Phinx internals that much, so I would like to know your opinion about it.

Do you think creating an adapter for ES would work?

**Comment by robmorgan** [comment]
@hgraca theoretically possible but since Phinx is so strongly engrained in SQL, it is best left to another tool.
