### ISSUE TITLE
Tag 0.5.4 release

### ISSUE THREAD

**Issue by michaldudek** [robmorgan/phinx#853]
It seems that changelog and commits include release `0.5.4` but it's not actually tagged and therefore not released in Packagist. This forces to use `"minimum-stability": "dev",` in `composer.json` in order to get this release which isn't viable :(

Could you please add a tag `0.5.4` so it can be released?

**Comment by rquadling** [comment]
Done

**Comment by robmorgan** [comment]
tag 0.5.4 was never pushed due to failing Travis builds however @rquadling has now fixed them. 👍
