### ISSUE TITLE
Question: How can I use Phinx as a library?

### ISSUE THREAD

**Issue by rakshazi** [robmorgan/phinx#856]
Hello!
My English is not very good, that's why let me start from description of my app:

My app is "cli" project (runs via cron) which maintain content for project (it parses files and inserts content to DB) and I want add db migrations functions to it with Phinx, but I don't know, how to do it right.
I wan't use Phinx in following way (pseudocode, just for example):
```php
<?php
Class MyApp
{
    public function migrate()
    {
        $config = array('database' => array(...), 'dir' => '/path/to/migrations');
        $phinx = new \Example\Phinx($config);
        try{
            $phinx->migrate();
        }catch(\Exception $e){
            $this->getLogger()->critical($e->getMessage());
        }
    }
}
```

How can I do that? I mean, how can I pass all configuration to Phinx as to any other library, without creating additional files?

Best regards, Nikita.

PS: I need only `migrate` and `rollback` commands

**Comment by rakshazi** [comment]
@robmorgan can you help me with this?

**Comment by rbalik** [comment]
Maybe this will help? http://docs.phinx.org/en/latest/commands.html#running-phinx-in-a-web-app

**Comment by rakshazi** [comment]
sorry, but no - here you need to pass php file with config, but I need pass
config array to Phinx object (without file)

пт, 10 июн. 2016 г. в 18:48, Reuben Balik <notifications@github.com>:

> Maybe this will help?
> http://docs.phinx.org/en/latest/commands.html#running-phinx-in-a-web-app
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/robmorgan/phinx/issues/856#issuecomment-225220089>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADRO995h1BJqUG80wpoZZdQDDJkMkjsDks5qKYdQgaJpZM4Iy-yX>
> .
>
-- 


[image: --]

Nikita Chernyi
[image: https://]about.me/nikus
<https://about.me/nikus?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

**Comment by rquadling** [comment]
The approach I use is to have the phinx commands as part of of my Symfony Console based application.

I use dependency injection to get hold of an instance of PhinxApplication, but you can use 

```php
$phinxApp = new \Phinx\Console\PhinxApplication;
```

As part of my application class's `doRun()` method, I have ...

```php
        $phinxCommands = [];
        foreach ($this->phinxApplication->all() as $commandName => $command) {
            $phinxCommands[] = $command->setName('phinx:'.str_replace(':', '-', $commandName));
        }
        $this->addCommands($phinxCommands);
```

At this point, running my app, I can see ``phinx:create`` (for example) as one of my commands.

Internally, to call a command, you can use http://symfony.com/doc/current/components/console/introduction.html#calling-an-existing-command

**Comment by rakshazi** [comment]
Hey, I solved problem:

### You need config file with db configs

> You can save your configs as you wish and just insert them into config array for Phinx, see my example

```php
<?php
$config = [
   // Any other configs
    'database' => [
        'database_type' => 'mysql',
        'database_name' => 'svart_xyz',
        'server' => 'database',
        'username' => 'root',
        'password' => 'password',
        'port' => 3306,
        'charset' => 'utf8',
        'option' => [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        ],
    ],
];

//Phinx config
$config['paths'] = ['migrations' => 'migrations'];
$config['environments'] = [
    "default_migration_table" => "phinxlog",
    "default_database" => "production",
    "production" => [
        "adapter" => $config['database']['database_type'],
        "host" => $config['database']['server'],
        "name" => $config['database']['database_name'],
        "user" => $config['database']['username'],
        "pass" => $config['database']['password'],
        "port" => $config['database']['port'],
        "charset" => $config['database']['charset'],
        "collaction" => "utf8_unicode_ci",
    ],
];

return $config;
```

### And just run Phinx from your class/file:

```php
public function migrate($command)
    {
        //You need set this var to "cheat" Symfony Console component and pass all needed params
        $_SERVER['argv'] = [
            'run.php', //Any string, doesn't matter
            $command, //Command to Phinx, in my case command may be only "migrate" or "rollback"
            '-c', $this->getConfigDir() . '/' . $this->getSite() . '.php', //Path to your config file
            '-e', 'production', //Selected Enviroment (in config file)
        ];
        $phinx = new \Phinx\Console\PhinxApplication();
        $phinx->run();
    }
```

That's all, it works as needed!
