### ISSUE TITLE
Ability to mark migration as done / rollback unfinished migrations

### ISSUE THREAD

**Issue by igorsantos07** [robmorgan/phinx#87]
Usually when writing migrations inside the Yii Framework, when I wrote something bad, the migration was left in an unfinished state: it wasn't added as "done" but I couldn't fix and re-run simply, because some of its changed were already applied to the database.
The solution to that was simple: I used `migrate mark XXX` and then `migrate rollback` to undo what was possible from that buggy migration. Then I fixed it and re-run normally.

Trying to use Phinx in a standalone project I got stuck in this same workflow: I cannot use Phinx to undo what I did wrong (cannot rollback a migration that wasn't finished) and thus I need to go inside the database to remove manually what was done bad - and this could be risky, as migrations are there to help us with working on the database.

Thus, if this case makes sense for you, I have two conflicting proposals:
- implement a "mark" command that would set a migration as done and then we could rollback it
- Phinx could intelligently rollback what was done when the database throws an error (could be easy in `change()` blocks at least, I think)

**Comment by robmorgan** [comment]
This will be fixed in #117.
