### ISSUE TITLE
Rollback crashes if you have only one migration

### ISSUE THREAD

**Issue by moritz-h** [robmorgan/phinx#873]
If i have only one migration (for example init database), migrate to this and then rollback i get the following error:

PHP Notice:  Undefined offset: -1 in [...]/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php on line 394
Target version () not found

I think perhaps this line creates an underflow when only one version exists:
https://github.com/robmorgan/phinx/blob/0.5.x-dev/src/Phinx/Migration/Manager.php#L374

**Comment by moritz-h** [comment]
Some more infos:
if i have 3 (and more) migrations and call rollback one migration in undone. (correct)
if i have only 2 migrations and call rollback the last two migrations are undone. (i think not correct)

**Comment by rquadling** [comment]
What version of Phinx are you using please?

**Comment by moritz-h** [comment]
v0.5.5.1 (what i get today from composer)

**Comment by rquadling** [comment]
Confirmed.

**Comment by moritz-h** [comment]
I saw you released 0.6 a few minutes ago. I tried it there. Bug is still the same so not only 0.5.5.1.

**Comment by rquadling** [comment]
Yep. Just fixing it now.

**Comment by rquadling** [comment]
v0.6.1

Sorry for this. Hope it didn't interfere with your day too much.

**Comment by moritz-h** [comment]
Thanks for the quick fix.

No problem I'm just new to phinx and noticed this while doing tutorials and hello world test :-)
