### ISSUE TITLE
MySQL enum values with special characters

### ISSUE THREAD

**Issue by odan** [robmorgan/phinx#887]
Hello

I'm trying to store some special values in a MySQL enum field like ' (single quote) and \ (backslash). Here is an example:

``` php
$this->table("test")->changeColumn('code', 'enum', array('values' => array('1','22','33','\'','"','\\','/',',',',,')))->update();`
```

**Error message**

`[PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that
   corresponds to your MariaDB server version for the right syntax to use near '"', '\', '/', ',', ',,') NULL COMMENT
   '4' AFTER`deleted`' at line 1
`  
**Query**

``` sql
ALTER TABLE `test` CHANGE `code` `code` ENUM('1', '22', '33', ''', '"', '\', '/', ',', ',,') NULL AFTER `deleted`
```

**Expected query:**

``` sql
ALTER TABLE `test` CHANGE `code` `code` ENUM('1', '22', '33', '\'', '"', '\\', '/', ',', ',,') NULL AFTER `deleted`
```

To make the query working I've added a backslash before ' and \.
' => \'
\ => \\
I think it's an small issue with a missing value escaping. How could I fix it?

Version: 0.6.2

**Comment by rquadling** [comment]
Hi.

If you want to make a Pull Request, then take a look at `\Phinx\Db\Adapter\MysqlAdapter::getColumnSqlDefinition()` and `\Phinx\Db\Adapter\SQLiteAdapter::getColumnSqlDefinition()`.

The iteration of the values returned by `$column->getValues()` need to be quoted.

`$def .= "('" . implode("', '", $values) . "')";`
becomes
`$def .= "('" . implode("', '", $this->getConnection()->quote($values)) . "')";`

and

`$def .= " CHECK({$column->getName()} IN ('" . implode("', '", $values) . "'))";`
becomes
`$def .= " CHECK({$column->getName()} IN ('" . implode("', '", $this->getConnection()->quote($values)) . "'))";`

Any unit tests that cover this code will need to be updated.

**Comment by rquadling** [comment]
Which is obviously wrong as each value in $values needs to be quoted. This is what happens when I've worked too many hours!!!!

**Comment by odan** [comment]
I try to create a PR.

**Comment by odan** [comment]
Here is my PR: https://github.com/robmorgan/phinx/pull/899
