### ISSUE TITLE
PostgreSQL error when issuing status

### ISSUE THREAD

**Issue by mbn18** [robmorgan/phinx#890]
I get the following error when issuing status after upgrading to `0.5.5` from `0.5.1`

>  [PDOException]                                                                                                                  
>  SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "breakpoint" is of type boolean but default expression is of type integer  
>  HINT:  You will need to rewrite or cast the expression.

**Comment by rquadling** [comment]
This was fixed in 0.6.2. As it required an additional method, a minor version bump was required.

**Comment by rquadling** [comment]
Basically, 0/1 work for mysql/sqlite/mssql but not postgres. 'true'/'false' work for postgres and one other (can't remember which one). I decided to go with 0/1 with postgres overriding the behaviour.

**Comment by mbn18** [comment]
Yes, working as expected with 0.6.2. Thanks
