### ISSUE TITLE
Support error retrieval when executing a batch of queries.

### ISSUE THREAD

**Issue by rquadling** [robmorgan/phinx#894]
Currently, Phinx does not support the reporting of errors for a batch of queries for the PDO based adpaters.

Utilising http://php.net/manual/en/pdostatement.nextrowset.php, it will be necessary to iterate the result set if a batch of results are available (as of writing this, I'm unsure how to determine that) to determine what errors are available.

One option is to inhibit batches of queries, but guaranteeing that in a consistent way may not be easy.

**Comment by jymboche** [comment]
I saw you made some documentation about this recently.... I had this issue with some scripts I had to process years ago and handled it by first instantiating PDO with these options:
```
$this->dbConnection = new PDO("mysql:host={$host};dbname={$db};", $user, $pass, array(
                PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_EMULATE_PREPARES=>true
            ));
```
then when executing the sql, just iterate over the nextRowSet(). It will throw an exception if there are errors in the query. No need to do anything in the while loop....
```
$db = $this->getConnection();
$db->beginTransaction();
$statement = $db->prepare($sql);
$statement->execute();
while($statement->nextRowset()) {
    /*
     * Fix for this issue
     * https://bugs.php.net/bug.php?id=61613
     */
}
$db->commit();
```
creating a transaction may or may not be desired. But is there a reason phinx couldnt implement it in this way?

**Comment by rquadling** [comment]
The approach you've suggested doesn't provide any mechanism to return the results to the caller. Not all migrations are fire and forget.

As PDO is fully exposed in Phix, there's nothing stopping a user from implementing the error checking themselves. Potentially, we could implement a proxy for nextResultSet() and throw the appropriate exception if an error was detected (thinking out loud on that one .... maybe it would help a little).

But there is no way to determine if a user has finished with a particular result set to allow us to move to the next one automatically and check the error state.

That must be triggered by the user when they are ready.

Hence the strong suggestion that queries are always singular.
