### ISSUE TITLE
Column id is missing!?

### ISSUE THREAD

**Issue by jeton-th** [robmorgan/phinx#895]
The id column that is supposed to be created automatically, is missing?
Here is the code:
`$users = $this->table('users');`
`$users  ->addColumn('email', 'string', array('limit' => 100))`
`             ->addColumn('password', 'string', array('limit' => 40))`
`             ->addColumn('name', 'string', array('limit' => 60))`
`             ->addColumn('active', 'boolean', array('default' => 0))`
`             ->addColumn('activation_key', 'string', array('limit' => 30))`
`             ->addColumn('created', 'datetime')`
`             ->addColumn('updated', 'datetime', array('null' => true))`
`             ->addIndex(array('email'), array('unique' => true))`
`             ->save();`
I'ts pretty much the example from the documentation (I tried that to) with a few changes, but it's not working?

**Comment by rquadling** [comment]
Try using `create()` and not `save()`.

**Comment by jeton-th** [comment]
I tried `create()` and I got:

> Base table or view already exists: 1050 Table 'users' already exists

Even though no table exists!?

**Comment by rquadling** [comment]
Do you have a view called `users`? The error is pretty specific. You could try changing to a new table name (as proof), say `my_users`. You will see the table created (use `create()` and not `save()` so rollback works as expected).

**Comment by rquadling** [comment]
When you run the migration and rollback, use the `-vvv` command line options to get some additional feedback.

**Comment by jeton-th** [comment]
Table successfully created with table name `my_users`.
But I don't understand ... why I can't use `users`???

**Comment by jeton-th** [comment]
Wow what a stupid mistake ... I was using `default_migration_table: users` in `phinx.yml` thats why the migration table was named `users` and it conflicted (merged) with the `users` table.

**Comment by rquadling** [comment]
Don't beat yourself up too much. We've all made mistakes.
