### ISSUE TITLE
Data Type mismatch exception on PostgreSQL 9.5

### ISSUE THREAD

**Issue by daniel-hinchliff** [robmorgan/phinx#897]
Column Datatype mismatch on version 0.5.5, going back to version 0.5.4 fixed the issue for me. This will happen even with an empty migrations folder, so it seems to be some bootstrapping issue. 

On Phinx by Rob Morgan - https://phinx.org. version 0.5.5

using config file .\phinx.php
using config parser php
using migration path db/migrations
warning no environment specified, defaulting to: development
using adapter pgsql
using database xxxxx

  [PDOException]
  SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  la columna ┬½breakpoint┬╗ es de

   tipo boolean pero la expresi├│n default es de tipo integer

  HINT:  Necesitar├í reescribir la expresi├│n o aplicarle una conversi├│n de tip

  o.

migrate [-c|--configuration CONFIGURATION] [-p|--parser PARSER] [-e|--environmen
t ENVIRONMENT] [-t|--target TARGET] [-d|--date DATE]

$ php --version
PHP 7.0.5 (cli) (built: Mar 30 2016 10:15:26) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans

**Comment by rquadling** [comment]
Fixed in 0.6.2
