### ISSUE TITLE
Datatype mismatch: 7 ERROR:  column "breakpoint" is of type boolean but expression is of type integer  

### ISSUE THREAD

**Issue by mkoula** [robmorgan/phinx#902]
I am using PostgeSQL and after running commands migrate|status I am getting this error:
`[PDOException]                                                                                                          
  SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "breakpoint" is of type boolean but expression is of type integer  
  LINE 1: ...tructure', '2016-07-14 02:42:52', '2016-07-14 02:42:52', 0);                                                 
                                                                      ^                                                   
  HINT:  You will need to rewrite or cast the expression.                                                                 
`

I tried to create new database and run init there and the migrations table has a new column breakpoint of type bool, the old one doesn't, so it's probably connected to some internal phinx upgrade...

![screen shot 2016-07-14 at 02 51 46](https://cloud.githubusercontent.com/assets/1447985/16824684/0c70fc5a-496e-11e6-86d5-d4adc79cba8a.png)

**Comment by rquadling** [comment]
Please upgrade to V0.6

**Comment by mkoula** [comment]
👍  thanks. I updated composer, but it has been holding the 0.5.x version so I had to manually edit it to 0.6.x and now it's working fine

**Comment by rquadling** [comment]
I think I'm going to have to back port a fix for 0.5 to allow it to work with postgres.

**Comment by mkoula** [comment]
No idea how much work it is. The problem is that the issue is not reported anywhere. I have been searching first and I could not find any resource, especially the error message is not super clear, after I played with the empty database and I saw 'breakpoint' in migration table I realised that will be connected. Nothing on stackoverlow etc. That's why I finally used github... So for other users could be a 👍

**Comment by rquadling** [comment]
What I'm not sure about is how a v0.5 got breakpoint support in any way as that was added in 0.6.

Are you able to check in your local composer cache what version/commit of phinx you had that generated the problem? If not, don't worry. I think I MAY have an answer, but if so, you were somehow loading a non-released version.
