### ISSUE TITLE
Insert with $this->insert('table', $rows); to an auto_increment field

### ISSUE THREAD

**Issue by ZaneCEO** [robmorgan/phinx#903]
I've `my_table` with a `id_table` primary key, auto_increment, not_null field.

On `up()`, I'm trying to[ insert into](http://docs.phinx.org/en/latest/migrations.html#inserting-data) this table with 
````
		$rows = [
            [
				'id_table'		=> null,
				.....
            ],
.....
        ];

$this->insert('table', $rows);
````

With that null, I'm trying to fire the auto_increment but all I get is `SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'id_table' cannot be null`.

I also tried to skip the field altogether: the first insert is successful with a zero value, but the second insert fails with ` SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'`.

What am I missing?

Thanks!

**Comment by rquadling** [comment]
Can you show the code for the table creation please? Both the migration and the SQL that the server says to use create the table?

Probably, the auto_inc / identity attribute is missing somewhere.

Also, what server are you using, this issue may relate to a single server/adpater.

**Comment by ZaneCEO** [comment]
Hi, thanks for your support!

I found out that the table's (also phinx-created) primary key was not really auto-increment. `'identity' => true` did the trick and now it works as expected.

So it's not a bug, it's just me being dumb :-/

**Comment by rquadling** [comment]
Is there anything in the documentation that could be improved with regard to this?

**Comment by ZaneCEO** [comment]
No, not really: the doc is good and explicit warns about the issue:

> Setting a single primary_key doesn’t enable the AUTO_INCREMENT option.

My error arose because  I needed to name the primary key `id_table` and not just `id` AND I also needed to set it unsigned, so initially I put it all in the table-creation statement... but then I had to split it  because (as far as I saw) the `signed` option is ignored on the table creation call.

The program logic is solid and the doc too, it's the developer (me) fault here.
