### ISSUE TITLE
Inserting seed files into database like phinxlog

### ISSUE THREAD

**Issue by onurdegerli** [robmorgan/phinx#931]
I integrated the phinx migrate command to Jenkins.
When Jenkins job runs, it starts to run all seed file from beginning.
Is it possible to insert seed files into any log files like migrations phinxlog?

**Comment by rquadling** [comment]
If you need seeds to act like migrations, then sureing making them migrations would be preferable?

**Comment by robmorgan** [comment]
yes @rquadling is right. If you want your INSERTS/seeder logic to only run once then thats what migrations are for. Please shift your logic there instead. If your looking for a logging feature to track when a seeder was run, you could use the functionality of Jenkins in the short term.
