### ISSUE TITLE
UnexpectedValueException when running migrate command

### ISSUE THREAD

**Issue by GhaziTriki** [robmorgan/phinx#934]
Hello,

After upgrading to version 0.6.4 then running "migrate" command I get the following error. I get the same error when rolling back.

![image](https://cloud.githubusercontent.com/assets/4991088/17552006/73c19708-5efd-11e6-8eb0-d4ec3fa3ea53.png)

**Comment by rquadling** [comment]
Hi.

Can you show the output of `vendor/bin/phinx test` and the content of your `phinx.yml` file (obscure any sensitive elements).

**Comment by GhaziTriki** [comment]
I have just fixed it. the first yml parameter name was `path` instead of `paths`. Probably the yml validation should be more clear.

**Comment by rquadling** [comment]
You say you upgraded to 0.6.4. What version were you on before?

**Comment by GhaziTriki** [comment]
I was using version 0.5.3

**Comment by rquadling** [comment]
OK. Thank you. I'll see what changed.

**Comment by GhaziTriki** [comment]
I think nothing has changed, when I had conflict on my `phinx.yml` I removed by mistake the `s` in `paths`, I already cehck that `paths` is used in that version.
