### ISSUE TITLE
Text Wrapper crashes without configuration

### ISSUE THREAD

**Issue by moritz-h** [robmorgan/phinx#959]
Running the text wrapper does not work like it is described in the Documentation: [LINK](http://docs.phinx.org/en/latest/commands.html#running-phinx-in-a-web-app)

When i just run `php -S localhost:8000 vendor/robmorgan/phinx/app/web.php` i get a `PHP Fatal error:  Uncaught Symfony\Component\Console\Exception\InvalidOptionException: The "--configuration" option requires a value.`
(I run this from my project root, there is also a phinx.php located)

It works when i additionally set some Options like this. (It also seems, that `default_database` from the config file is ignored, and i need to set the 'environment' option.)

``` php
$app = new \Phinx\Console\PhinxApplication();
$wrap = new \Phinx\Wrapper\TextWrapper($app);
$wrap->setOption('configuration', 'phinx.php');
$wrap->setOption('parser', 'php');
$wrap->setOption('environment', 'db');

echo $wrap->getStatus();
echo $wrap->getRollback(null, 0);
echo $wrap->getMigrate();
echo $wrap->getSeed();
```

So ether this is a bug, that the text wrapper crashes without setting configuration, or if the text wrapper needs the configuration this should be mentioned in the documentation.

Edit: Version is 0.6.4

**Comment by piotr-cz** [comment]
Same in 0.8.0

**Comment by rquadling** [comment]
@piotr-cz If you set the path in `$wrap->setOption('configuration', '/path/to/phinx.php');` does this work appropriately?

**Comment by piotr-cz** [comment]
Yes, it does, like that::
```php
$app = new \Phinx\Console\PhinxApplication();
$wrap = new \Phinx\Wrapper\TextWrapper($app, [
    'configuration' => $appSettings['root'] . '/phinx.php'
]);
```
