### ISSUE TITLE
Text Wrapper crashes when calling rollback twice

### ISSUE THREAD

**Issue by moritz-h** [robmorgan/phinx#960]
When i try to call getRollback twice on a text wrapper i get a `Symfony\Component\Console\Exception\RuntimeException: Unable to write output.` Exception.

Example:

``` php
$app = new \Phinx\Console\PhinxApplication();
$wrap = new \Phinx\Wrapper\TextWrapper($app);
$wrap->setOption('environment', 'db');
$wrap->setOption('configuration', 'phinx.php');
$wrap->setOption('parser', 'php');

echo $wrap->getRollback(null, 0);
echo $wrap->getMigrate();
echo $wrap->getRollback(null, 0); // <- exception here
```

When i setup a new wrapper in between it works:

``` php
$app = new \Phinx\Console\PhinxApplication();
$wrap = new \Phinx\Wrapper\TextWrapper($app);
$wrap->setOption('environment', 'db');
$wrap->setOption('configuration', 'phinx.php');
$wrap->setOption('parser', 'php');

echo $wrap->getRollback(null, 0);
echo $wrap->getMigrate();

$app = new \Phinx\Console\PhinxApplication();
$wrap = new \Phinx\Wrapper\TextWrapper($app);
$wrap->setOption('environment', 'db');
$wrap->setOption('configuration', 'phinx.php');
$wrap->setOption('parser', 'php');

echo $wrap->getRollback(null, 0); // <- no exception here
```

Edit: Version is 0.6.4

**Comment by robmorgan** [comment]
hi @moritz-h, what are you putting in your `phinx.php` file?

**Comment by moritz-h** [comment]
@robmorgan I created a minimal example: https://gist.github.com/moritz-h/579f43c8af02f3644115d91185b73f6e
(The `20160922000000_init_db.php ` file should be in a `migrations` subdirectory, could not name it with path in the gist.)

I run `composer install` and start it with `php -S localhost:8000 index.php`.

The database settings in the phinx.php match to an existing mysql database and my php version is `7.0.8` (default Ubuntu 16.04).

**Comment by moritz-h** [comment]
@robmorgan I found out where this error comes from:

The TextWrapper creates a new Output Instance for each call:
https://github.com/robmorgan/phinx/blob/master/src/Phinx/Wrapper/TextWrapper.php#L215

This OutputInterface Object is recieved by execute() of a command (i.e. Status) and then passed to bootstrap()
https://github.com/robmorgan/phinx/blob/master/src/Phinx/Console/Command/Status.php#L68-L70

AbstractCommand::bootstrap() passes this to AbstractCommand::loadManager() where a new Manager object is created, but only if no Manager was created before:
https://github.com/robmorgan/phinx/blob/master/src/Phinx/Console/Command/AbstractCommand.php#L285-L288

The Manager object saves the OutputInterface as property. And that is the source of the error.
If i call the command a second time the TextWrapper creates a new OutputInterface and passes this to the command. But the command then has cached the Manager with the reference to the old OutputInterface from the first call.

To fix this, it would be possible to here create always a new Manager:
https://github.com/robmorgan/phinx/blob/master/src/Phinx/Console/Command/AbstractCommand.php#L285-L288
But i don't know if this would has any other bad side effects.
Otherwise perhaps its possible to just update the InputInterface and OutputInterface of the Manager.
Or perhaps the TextWrapper also should reuse the same OutputInterface for all command calls.
(Then with Symfony\Component\Console\Output\BufferedOutput instead of Symfony\Component\Console\Output\StreamOutput no not mess up with fopen)
