### ISSUE TITLE
PHP7 Weird bug

### ISSUE THREAD

**Issue by frazr** [robmorgan/phinx#964]
Getting glob_brace error running phinx 0.5.3 which is default version in CakePHP 3 on first server, if i fix the issue in Manager.php the migrations goes through without errors.

On second server there is no error in Manager.php with the same PHP version as you can see in the link below. Instead the migration crashes on a MigrationFile which is also included in the gist below.

https://gist.github.com/anonymous/a54c4fb2dd52b1ec2541878da84394e0

**Comment by shadowhand** [comment]
What kind of a server are you using? According to PHP docs:

> Note: The `GLOB_BRACE` flag is not available on some non GNU systems, like Solaris.

**Comment by rquadling** [comment]
https://github.com/robmorgan/phinx/commit/b4cc87eee3d398539c48c39a546438ece85ddb71

This has been fixed. Can you try upgrading Phinx?

**Comment by rquadling** [comment]
If you do upgrade, please read https://github.com/robmorgan/phinx/blob/0.6.x-dev/UPGRADE_0.6.md

**Comment by rquadling** [comment]
Closing issue as resolved. Please re-open with additional details if you still experience the problem once you've upgraded.
